import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_test/flutter_test.dart';

import 'package:submersion/core/services/geocoding/sea_area_index.dart';
import 'package:submersion/core/services/geocoding/sea_area_service.dart';

/// Invariants over the shipped ocean and sea table, plus the behaviour that
/// actually matters to a diver: real dive sites get the name they would
/// write themselves, and inland sites get nothing rather than a wrong sea.
///
/// The table is regenerated by `scripts/sea_area_harvester.py`; a generator
/// that starts emitting unsorted areas, empty rings or a shifted coastline
/// fails here rather than on a diver's phone.
void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late SeaAreaIndex index;

  setUpAll(() async {
    SeaAreaService.resetCacheForTesting();
    final loaded = await SeaAreaService.load();
    expect(loaded, isNotNull, reason: 'the sea area asset must be bundled');
    index = loaded!;
  });

  tearDownAll(SeaAreaService.resetCacheForTesting);

  group('dataset invariants', () {
    test('carries the full IHO set', () {
      expect(index.areas.length, greaterThanOrEqualTo(100));
    });

    test('is sorted ascending by area, which is the precedence rule', () {
      for (var i = 1; i < index.areas.length; i++) {
        expect(
          index.areas[i].areaSquareDegrees,
          greaterThanOrEqualTo(index.areas[i - 1].areaSquareDegrees),
          reason: 'area ${index.areas[i].name} is out of order',
        );
      }
    });

    test('every area is named, closed and inside the world', () {
      for (final area in index.areas) {
        final where = area.name;
        expect(area.name.trim(), isNotEmpty, reason: 'blank name');
        expect(area.polygons, isNotEmpty, reason: 'no polygons: $where');
        expect(area.minLon, greaterThanOrEqualTo(-180), reason: where);
        expect(area.maxLon, lessThanOrEqualTo(180), reason: where);
        expect(area.minLat, greaterThanOrEqualTo(-90), reason: where);
        expect(area.maxLat, lessThanOrEqualTo(90), reason: where);

        for (final polygon in area.polygons) {
          for (final ring in [polygon.outer, ...polygon.holes]) {
            expect(
              ring.vertexCount,
              greaterThanOrEqualTo(3),
              reason: 'degenerate ring in $where',
            );
            expect(
              ring.coordinates.first,
              ring.coordinates[ring.coordinates.length - 2],
              reason: 'unclosed ring longitude in $where',
            );
            expect(
              ring.coordinates[1],
              ring.coordinates.last,
              reason: 'unclosed ring latitude in $where',
            );
          }
        }
      }
    });

    test('stamps metadata a parser can actually read', () async {
      // The generator used to append "Z" to an isoformat() that already
      // carried "+00:00", producing a timestamp no ISO-8601 parser accepts.
      // This asserts the shipped file, not just the generator.
      final raw = await rootBundle.loadString(SeaAreaService.assetPath);
      final metadata =
          (jsonDecode(raw) as Map<String, dynamic>)['metadata']
              as Map<String, dynamic>;

      final stamp = metadata['generated_at'] as String;
      expect(stamp, endsWith('Z'));
      expect(stamp, isNot(contains('+00:00')));
      expect(DateTime.parse(stamp).isUtc, isTrue);

      expect(metadata['license'], 'CC-BY 4.0');
      expect(metadata['citation'], contains('Flanders Marine Institute'));
      expect(metadata['total_count'], index.areas.length);
    });

    test('uses the names a diver writes, not the IHO labels', () {
      final names = index.areas.map((a) => a.name).toSet();
      expect(names, contains('Mediterranean Sea'));
      expect(names, contains('Andaman Sea'));
      expect(names, contains('Sea of Japan'));
      expect(names, contains('East China Sea'));
      expect(names, isNot(contains('Mediterranean Sea - Western Basin')));
      expect(names, isNot(contains('Andaman or Burma Sea')));
      expect(names, isNot(contains('Barentsz Sea')));
    });
  });

  group('real dive sites resolve', () {
    // Coordinates of well-known sites, with the name IHO gives that water.
    const sites = <String, (double, double, String)>{
      'Belize Blue Hole': (16.5225, -87.9333, 'Caribbean Sea'),
      'Ras Mohammed': (27.7275, 34.2544, 'Red Sea'),
      'Dahab Blue Hole': (28.5722, 34.5372, 'Gulf of Aqaba'),
      'Cozumel Palancar': (20.3400, -87.0300, 'Caribbean Sea'),
      'Bonaire 1000 Steps': (12.2100, -68.3300, 'Caribbean Sea'),
      'Key Largo': (25.0700, -80.3000, 'North Atlantic Ocean'),
      'Sipadan': (4.1150, 118.6285, 'Celebes Sea'),
      'Great Barrier Reef': (-14.6700, 145.6300, 'Coral Sea'),
      'Poor Knights': (-35.4667, 174.7333, 'South Pacific Ocean'),
      'Similan Islands': (8.6500, 97.6400, 'Andaman Sea'),
      'Maldives Ari Atoll': (3.8000, 72.8300, 'Laccadive Sea'),
      'Sodwana Bay': (-27.5300, 32.6900, 'Indian Ocean'),
      'Cape Town': (-34.1400, 18.3300, 'South Atlantic Ocean'),
      'Azores': (38.0000, -29.2000, 'North Atlantic Ocean'),
      'Malta': (35.8200, 14.4400, 'Mediterranean Sea'),
      'Vis, Croatia': (43.0200, 16.1500, 'Adriatic Sea'),
      'Santorini': (36.3900, 25.4300, 'Aegean Sea'),
      'Elba': (42.7600, 10.2000, 'Tyrrhenian Sea'),
      'Scapa Flow': (58.9000, -3.1800, 'North Sea'),
      'Baltic, Poland': (54.7500, 18.6000, 'Baltic Sea'),
      'Lofoten': (68.2000, 13.6000, 'Norwegian Sea'),
      'La Paz': (24.2900, -110.3200, 'Gulf of California'),
      'Catalina Island': (33.3450, -118.3260, 'North Pacific Ocean'),
      'Monterey': (36.6100, -121.8940, 'North Pacific Ocean'),
      'Truk Lagoon': (7.4000, 151.8500, 'North Pacific Ocean'),
      'Okinawa': (26.5000, 127.8500, 'East China Sea'),
      'Komodo': (-8.5230, 119.6300, 'Savu Sea'),
    };

    for (final entry in sites.entries) {
      test(entry.key, () {
        final (lat, lon, expected) = entry.value;
        expect(index.nameAt(lat, lon), expected);
      });
    }
  });

  group('inland and fresh water resolve to nothing', () {
    // Null here is the correct answer, not a gap: the online natural-layer
    // lookup names lakes and quarries well, and a wrong sea is worse than
    // an empty field.
    const sites = <String, (double, double)>{
      'Lake Geneva': (46.4500, 6.5000),
      'Attersee, Austria': (47.8700, 13.5500),
      'Silvaplana, Switzerland': (46.4500, 9.7900),
      'Hemmoor quarry, Germany': (53.6900, 9.1400),
      'Ginnie Springs, Florida': (29.8360, -82.7000),
      'Cenote Dos Ojos': (20.3230, -87.3900),
      'Lake Michigan': (43.0000, -87.0000),
      'Lake Tahoe': (39.0900, -120.0400),
      'Lake Baikal': (53.5000, 108.0000),
      'Munich': (48.1370, 11.5750),
    };

    for (final entry in sites.entries) {
      test(entry.key, () {
        final (lat, lon) = entry.value;
        expect(index.nameAt(lat, lon), isNull);
      });
    }
  });

  group('names in the diver\'s language', () {
    // Every other geocoded field honours PlaceNameLanguage, so the table
    // has to as well or one column ends up holding two languages.
    test('answers in the requested language', () {
      expect(index.nameAt(27.7275, 34.2544, languageCode: 'de'), 'Rotes Meer');
      expect(index.nameAt(27.7275, 34.2544, languageCode: 'fr'), 'mer Rouge');
      expect(index.nameAt(27.7275, 34.2544, languageCode: 'zh'), '红海');
    });

    test('defaults to English', () {
      expect(index.nameAt(27.7275, 34.2544), 'Red Sea');
      expect(index.nameAt(27.7275, 34.2544, languageCode: 'en'), 'Red Sea');
    });

    test('falls back to English for a language it has no name in', () {
      // A synced peer on a newer build could ask for anything.
      expect(index.nameAt(27.7275, 34.2544, languageCode: 'xx'), 'Red Sea');
      expect(index.nameAt(27.7275, 34.2544, languageCode: ''), 'Red Sea');
    });

    test('localizes the near-shore answer too, not just containment', () {
      // Ras Mohammed is outside the IHO limit and resolved by proximity.
      expect(index.nameAt(27.7275, 34.2544), 'Red Sea');
      expect(
        index.nameAt(12.21, -68.33, languageCode: 'de'),
        isNot('Caribbean Sea'),
      );
      expect(
        index.nameAt(12.21, -68.33, languageCode: 'de'),
        contains('Karibisch'),
      );
    });

    test('every area carries an English name, and most carry the rest', () {
      final counts = <String, int>{};
      for (final area in index.areas) {
        expect(area.name.trim(), isNotEmpty);
        for (final code in area.localizedNames.keys) {
          counts[code] = (counts[code] ?? 0) + 1;
        }
        expect(
          area.localizedNames.containsKey('en'),
          isFalse,
          reason: 'English lives in name, not in the map: ${area.name}',
        );
      }
      // Hungarian is the thinnest at roughly five sixths; the rest are
      // near total. A collapse here means the harvester lost its labels.
      for (final code in [
        'es',
        'fr',
        'de',
        'it',
        'nl',
        'pt',
        'ar',
        'he',
        'zh',
      ]) {
        expect(
          counts[code] ?? 0,
          greaterThanOrEqualTo(90),
          reason: 'thin coverage for \$code',
        );
      }
      expect(counts['hu'] ?? 0, greaterThanOrEqualTo(80));
    });

    test('no label carries a typographic ligature', () {
      // The French Pacific labels arrive from Wikidata with U+FB01.
      for (final area in index.areas) {
        for (final entry in area.localizedNames.entries) {
          expect(
            entry.value.contains('\uFB01'),
            isFalse,
            reason: '${area.name} ${entry.key} has an unnormalized ligature',
          );
          expect(entry.value.trim(), entry.value);
        }
      }
    });
  });

  group('the antimeridian and the poles', () {
    // The Pacific, Bering and Chukchi polygons are split at 180 degrees,
    // while the Arctic and Southern oceans are single circumpolar rings
    // that close along the top and bottom edges. Ray casting is done in
    // flat lon/lat space, so both shapes have to come out right.
    test('resolves on both sides of the antimeridian', () {
      expect(index.nameAt(0, 179.5), 'North Pacific Ocean');
      expect(index.nameAt(0, -179.5), 'North Pacific Ocean');
      expect(index.nameAt(0, 180), 'North Pacific Ocean');
    });

    test('resolves a split sea across the seam', () {
      expect(index.nameAt(60, 179), 'Bering Sea');
      expect(index.nameAt(60, -179), 'Bering Sea');
    });

    test('resolves the circumpolar rings', () {
      expect(index.nameAt(89.9, 0), 'Arctic Ocean');
      expect(index.nameAt(85, 180), 'Arctic Ocean');
      expect(index.nameAt(-70, 0), 'Southern Ocean');
      expect(index.nameAt(-75, 175), 'Southern Ocean');
    });

    test('the South Pole is land, so it has no sea', () {
      expect(index.nameAt(-89.9, 0), isNull);
    });
  });

  group('Pacific island destinations', () {
    // Small islands are not carved out of the ocean polygons, so a site
    // just off one still reports the ocean around it.
    const sites = <String, (double, double, String)>{
      'Fiji Beqa Lagoon': (-18.40, 178.05, 'South Pacific Ocean'),
      'Fiji Bligh Water': (-17.20, 178.20, 'South Pacific Ocean'),
      'Tonga Vavau': (-18.65, -173.98, 'South Pacific Ocean'),
      'Rarotonga': (-21.23, -159.78, 'South Pacific Ocean'),
      'Fakarava': (-16.05, -145.62, 'South Pacific Ocean'),
      'Vanuatu Espiritu Santo': (-15.52, 167.17, 'Coral Sea'),
      'New Caledonia': (-22.30, 166.45, 'Coral Sea'),
      'Solomon Islands': (-8.10, 157.00, 'Solomon Sea'),
      'Hawaii, Kona': (19.60, -156.05, 'North Pacific Ocean'),
      'Galapagos': (1.68, -91.99, 'North Pacific Ocean'),
    };

    for (final entry in sites.entries) {
      test(entry.key, () {
        final (lat, lon, expected) = entry.value;
        expect(index.nameAt(lat, lon), expected);
      });
    }
  });

  test('names the more specific sea where two limits meet', () {
    // The Gulf of Aqaba sits inside the Red Sea's bounding box; the
    // smallest-area rule has to prefer the gulf.
    expect(index.nameAt(29.0, 34.7), 'Gulf of Aqaba');
    expect(index.nameAt(24.0, 36.0), 'Red Sea');
  });
}
