// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "dive_computer_api.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace libdivecomputer_plugin {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

// DeviceDescriptor

DeviceDescriptor::DeviceDescriptor(
  const std::string& vendor,
  const std::string& product,
  int64_t model,
  const EncodableList& transports)
 : vendor_(vendor),
    product_(product),
    model_(model),
    transports_(transports) {}

const std::string& DeviceDescriptor::vendor() const {
  return vendor_;
}

void DeviceDescriptor::set_vendor(std::string_view value_arg) {
  vendor_ = value_arg;
}


const std::string& DeviceDescriptor::product() const {
  return product_;
}

void DeviceDescriptor::set_product(std::string_view value_arg) {
  product_ = value_arg;
}


int64_t DeviceDescriptor::model() const {
  return model_;
}

void DeviceDescriptor::set_model(int64_t value_arg) {
  model_ = value_arg;
}


const EncodableList& DeviceDescriptor::transports() const {
  return transports_;
}

void DeviceDescriptor::set_transports(const EncodableList& value_arg) {
  transports_ = value_arg;
}


EncodableList DeviceDescriptor::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(EncodableValue(vendor_));
  list.push_back(EncodableValue(product_));
  list.push_back(EncodableValue(model_));
  list.push_back(EncodableValue(transports_));
  return list;
}

DeviceDescriptor DeviceDescriptor::FromEncodableList(const EncodableList& list) {
  DeviceDescriptor decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::get<int64_t>(list[2]),
    std::get<EncodableList>(list[3]));
  return decoded;
}

// DiscoveredDevice

DiscoveredDevice::DiscoveredDevice(
  const std::string& vendor,
  const std::string& product,
  int64_t model,
  const std::string& address,
  const TransportType& transport)
 : vendor_(vendor),
    product_(product),
    model_(model),
    address_(address),
    transport_(transport) {}

DiscoveredDevice::DiscoveredDevice(
  const std::string& vendor,
  const std::string& product,
  int64_t model,
  const std::string& address,
  const std::string* name,
  const TransportType& transport)
 : vendor_(vendor),
    product_(product),
    model_(model),
    address_(address),
    name_(name ? std::optional<std::string>(*name) : std::nullopt),
    transport_(transport) {}

const std::string& DiscoveredDevice::vendor() const {
  return vendor_;
}

void DiscoveredDevice::set_vendor(std::string_view value_arg) {
  vendor_ = value_arg;
}


const std::string& DiscoveredDevice::product() const {
  return product_;
}

void DiscoveredDevice::set_product(std::string_view value_arg) {
  product_ = value_arg;
}


int64_t DiscoveredDevice::model() const {
  return model_;
}

void DiscoveredDevice::set_model(int64_t value_arg) {
  model_ = value_arg;
}


const std::string& DiscoveredDevice::address() const {
  return address_;
}

void DiscoveredDevice::set_address(std::string_view value_arg) {
  address_ = value_arg;
}


const std::string* DiscoveredDevice::name() const {
  return name_ ? &(*name_) : nullptr;
}

void DiscoveredDevice::set_name(const std::string_view* value_arg) {
  name_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void DiscoveredDevice::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const TransportType& DiscoveredDevice::transport() const {
  return transport_;
}

void DiscoveredDevice::set_transport(const TransportType& value_arg) {
  transport_ = value_arg;
}


EncodableList DiscoveredDevice::ToEncodableList() const {
  EncodableList list;
  list.reserve(6);
  list.push_back(EncodableValue(vendor_));
  list.push_back(EncodableValue(product_));
  list.push_back(EncodableValue(model_));
  list.push_back(EncodableValue(address_));
  list.push_back(name_ ? EncodableValue(*name_) : EncodableValue());
  list.push_back(CustomEncodableValue(transport_));
  return list;
}

DiscoveredDevice DiscoveredDevice::FromEncodableList(const EncodableList& list) {
  DiscoveredDevice decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::get<int64_t>(list[2]),
    std::get<std::string>(list[3]),
    std::any_cast<const TransportType&>(std::get<CustomEncodableValue>(list[5])));
  auto& encodable_name = list[4];
  if (!encodable_name.IsNull()) {
    decoded.set_name(std::get<std::string>(encodable_name));
  }
  return decoded;
}

// ProfileSample

ProfileSample::ProfileSample(
  int64_t time_seconds,
  double depth_meters)
 : time_seconds_(time_seconds),
    depth_meters_(depth_meters) {}

ProfileSample::ProfileSample(
  int64_t time_seconds,
  double depth_meters,
  const double* temperature_celsius,
  const double* pressure_bar,
  const int64_t* tank_index,
  const EncodableList* tank_pressures_bar,
  const int64_t* heart_rate,
  const double* heading,
  const double* setpoint,
  const double* ppo2,
  const double* cns,
  const int64_t* rbt,
  const int64_t* deco_type,
  const int64_t* deco_time,
  const double* deco_depth,
  const int64_t* tts,
  const double* o2_sensor1,
  const double* o2_sensor2,
  const double* o2_sensor3,
  const double* o2_sensor4,
  const double* o2_sensor5,
  const double* o2_sensor6,
  const int64_t* o2_sensor_mv1,
  const int64_t* o2_sensor_mv2,
  const int64_t* o2_sensor_mv3,
  const int64_t* o2_sensor_mv4,
  const int64_t* o2_sensor_mv5,
  const int64_t* o2_sensor_mv6,
  const int64_t* gas_mix_index)
 : time_seconds_(time_seconds),
    depth_meters_(depth_meters),
    temperature_celsius_(temperature_celsius ? std::optional<double>(*temperature_celsius) : std::nullopt),
    pressure_bar_(pressure_bar ? std::optional<double>(*pressure_bar) : std::nullopt),
    tank_index_(tank_index ? std::optional<int64_t>(*tank_index) : std::nullopt),
    tank_pressures_bar_(tank_pressures_bar ? std::optional<EncodableList>(*tank_pressures_bar) : std::nullopt),
    heart_rate_(heart_rate ? std::optional<int64_t>(*heart_rate) : std::nullopt),
    heading_(heading ? std::optional<double>(*heading) : std::nullopt),
    setpoint_(setpoint ? std::optional<double>(*setpoint) : std::nullopt),
    ppo2_(ppo2 ? std::optional<double>(*ppo2) : std::nullopt),
    cns_(cns ? std::optional<double>(*cns) : std::nullopt),
    rbt_(rbt ? std::optional<int64_t>(*rbt) : std::nullopt),
    deco_type_(deco_type ? std::optional<int64_t>(*deco_type) : std::nullopt),
    deco_time_(deco_time ? std::optional<int64_t>(*deco_time) : std::nullopt),
    deco_depth_(deco_depth ? std::optional<double>(*deco_depth) : std::nullopt),
    tts_(tts ? std::optional<int64_t>(*tts) : std::nullopt),
    o2_sensor1_(o2_sensor1 ? std::optional<double>(*o2_sensor1) : std::nullopt),
    o2_sensor2_(o2_sensor2 ? std::optional<double>(*o2_sensor2) : std::nullopt),
    o2_sensor3_(o2_sensor3 ? std::optional<double>(*o2_sensor3) : std::nullopt),
    o2_sensor4_(o2_sensor4 ? std::optional<double>(*o2_sensor4) : std::nullopt),
    o2_sensor5_(o2_sensor5 ? std::optional<double>(*o2_sensor5) : std::nullopt),
    o2_sensor6_(o2_sensor6 ? std::optional<double>(*o2_sensor6) : std::nullopt),
    o2_sensor_mv1_(o2_sensor_mv1 ? std::optional<int64_t>(*o2_sensor_mv1) : std::nullopt),
    o2_sensor_mv2_(o2_sensor_mv2 ? std::optional<int64_t>(*o2_sensor_mv2) : std::nullopt),
    o2_sensor_mv3_(o2_sensor_mv3 ? std::optional<int64_t>(*o2_sensor_mv3) : std::nullopt),
    o2_sensor_mv4_(o2_sensor_mv4 ? std::optional<int64_t>(*o2_sensor_mv4) : std::nullopt),
    o2_sensor_mv5_(o2_sensor_mv5 ? std::optional<int64_t>(*o2_sensor_mv5) : std::nullopt),
    o2_sensor_mv6_(o2_sensor_mv6 ? std::optional<int64_t>(*o2_sensor_mv6) : std::nullopt),
    gas_mix_index_(gas_mix_index ? std::optional<int64_t>(*gas_mix_index) : std::nullopt) {}

int64_t ProfileSample::time_seconds() const {
  return time_seconds_;
}

void ProfileSample::set_time_seconds(int64_t value_arg) {
  time_seconds_ = value_arg;
}


double ProfileSample::depth_meters() const {
  return depth_meters_;
}

void ProfileSample::set_depth_meters(double value_arg) {
  depth_meters_ = value_arg;
}


const double* ProfileSample::temperature_celsius() const {
  return temperature_celsius_ ? &(*temperature_celsius_) : nullptr;
}

void ProfileSample::set_temperature_celsius(const double* value_arg) {
  temperature_celsius_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ProfileSample::set_temperature_celsius(double value_arg) {
  temperature_celsius_ = value_arg;
}


const double* ProfileSample::pressure_bar() const {
  return pressure_bar_ ? &(*pressure_bar_) : nullptr;
}

void ProfileSample::set_pressure_bar(const double* value_arg) {
  pressure_bar_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ProfileSample::set_pressure_bar(double value_arg) {
  pressure_bar_ = value_arg;
}


const int64_t* ProfileSample::tank_index() const {
  return tank_index_ ? &(*tank_index_) : nullptr;
}

void ProfileSample::set_tank_index(const int64_t* value_arg) {
  tank_index_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ProfileSample::set_tank_index(int64_t value_arg) {
  tank_index_ = value_arg;
}


const EncodableList* ProfileSample::tank_pressures_bar() const {
  return tank_pressures_bar_ ? &(*tank_pressures_bar_) : nullptr;
}

void ProfileSample::set_tank_pressures_bar(const EncodableList* value_arg) {
  tank_pressures_bar_ = value_arg ? std::optional<EncodableList>(*value_arg) : std::nullopt;
}

void ProfileSample::set_tank_pressures_bar(const EncodableList& value_arg) {
  tank_pressures_bar_ = value_arg;
}


const int64_t* ProfileSample::heart_rate() const {
  return heart_rate_ ? &(*heart_rate_) : nullptr;
}

void ProfileSample::set_heart_rate(const int64_t* value_arg) {
  heart_rate_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ProfileSample::set_heart_rate(int64_t value_arg) {
  heart_rate_ = value_arg;
}


const double* ProfileSample::heading() const {
  return heading_ ? &(*heading_) : nullptr;
}

void ProfileSample::set_heading(const double* value_arg) {
  heading_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ProfileSample::set_heading(double value_arg) {
  heading_ = value_arg;
}


const double* ProfileSample::setpoint() const {
  return setpoint_ ? &(*setpoint_) : nullptr;
}

void ProfileSample::set_setpoint(const double* value_arg) {
  setpoint_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ProfileSample::set_setpoint(double value_arg) {
  setpoint_ = value_arg;
}


const double* ProfileSample::ppo2() const {
  return ppo2_ ? &(*ppo2_) : nullptr;
}

void ProfileSample::set_ppo2(const double* value_arg) {
  ppo2_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ProfileSample::set_ppo2(double value_arg) {
  ppo2_ = value_arg;
}


const double* ProfileSample::cns() const {
  return cns_ ? &(*cns_) : nullptr;
}

void ProfileSample::set_cns(const double* value_arg) {
  cns_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ProfileSample::set_cns(double value_arg) {
  cns_ = value_arg;
}


const int64_t* ProfileSample::rbt() const {
  return rbt_ ? &(*rbt_) : nullptr;
}

void ProfileSample::set_rbt(const int64_t* value_arg) {
  rbt_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ProfileSample::set_rbt(int64_t value_arg) {
  rbt_ = value_arg;
}


const int64_t* ProfileSample::deco_type() const {
  return deco_type_ ? &(*deco_type_) : nullptr;
}

void ProfileSample::set_deco_type(const int64_t* value_arg) {
  deco_type_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ProfileSample::set_deco_type(int64_t value_arg) {
  deco_type_ = value_arg;
}


const int64_t* ProfileSample::deco_time() const {
  return deco_time_ ? &(*deco_time_) : nullptr;
}

void ProfileSample::set_deco_time(const int64_t* value_arg) {
  deco_time_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ProfileSample::set_deco_time(int64_t value_arg) {
  deco_time_ = value_arg;
}


const double* ProfileSample::deco_depth() const {
  return deco_depth_ ? &(*deco_depth_) : nullptr;
}

void ProfileSample::set_deco_depth(const double* value_arg) {
  deco_depth_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ProfileSample::set_deco_depth(double value_arg) {
  deco_depth_ = value_arg;
}


const int64_t* ProfileSample::tts() const {
  return tts_ ? &(*tts_) : nullptr;
}

void ProfileSample::set_tts(const int64_t* value_arg) {
  tts_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ProfileSample::set_tts(int64_t value_arg) {
  tts_ = value_arg;
}


const double* ProfileSample::o2_sensor1() const {
  return o2_sensor1_ ? &(*o2_sensor1_) : nullptr;
}

void ProfileSample::set_o2_sensor1(const double* value_arg) {
  o2_sensor1_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ProfileSample::set_o2_sensor1(double value_arg) {
  o2_sensor1_ = value_arg;
}


const double* ProfileSample::o2_sensor2() const {
  return o2_sensor2_ ? &(*o2_sensor2_) : nullptr;
}

void ProfileSample::set_o2_sensor2(const double* value_arg) {
  o2_sensor2_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ProfileSample::set_o2_sensor2(double value_arg) {
  o2_sensor2_ = value_arg;
}


const double* ProfileSample::o2_sensor3() const {
  return o2_sensor3_ ? &(*o2_sensor3_) : nullptr;
}

void ProfileSample::set_o2_sensor3(const double* value_arg) {
  o2_sensor3_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ProfileSample::set_o2_sensor3(double value_arg) {
  o2_sensor3_ = value_arg;
}


const double* ProfileSample::o2_sensor4() const {
  return o2_sensor4_ ? &(*o2_sensor4_) : nullptr;
}

void ProfileSample::set_o2_sensor4(const double* value_arg) {
  o2_sensor4_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ProfileSample::set_o2_sensor4(double value_arg) {
  o2_sensor4_ = value_arg;
}


const double* ProfileSample::o2_sensor5() const {
  return o2_sensor5_ ? &(*o2_sensor5_) : nullptr;
}

void ProfileSample::set_o2_sensor5(const double* value_arg) {
  o2_sensor5_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ProfileSample::set_o2_sensor5(double value_arg) {
  o2_sensor5_ = value_arg;
}


const double* ProfileSample::o2_sensor6() const {
  return o2_sensor6_ ? &(*o2_sensor6_) : nullptr;
}

void ProfileSample::set_o2_sensor6(const double* value_arg) {
  o2_sensor6_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ProfileSample::set_o2_sensor6(double value_arg) {
  o2_sensor6_ = value_arg;
}


const int64_t* ProfileSample::o2_sensor_mv1() const {
  return o2_sensor_mv1_ ? &(*o2_sensor_mv1_) : nullptr;
}

void ProfileSample::set_o2_sensor_mv1(const int64_t* value_arg) {
  o2_sensor_mv1_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ProfileSample::set_o2_sensor_mv1(int64_t value_arg) {
  o2_sensor_mv1_ = value_arg;
}


const int64_t* ProfileSample::o2_sensor_mv2() const {
  return o2_sensor_mv2_ ? &(*o2_sensor_mv2_) : nullptr;
}

void ProfileSample::set_o2_sensor_mv2(const int64_t* value_arg) {
  o2_sensor_mv2_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ProfileSample::set_o2_sensor_mv2(int64_t value_arg) {
  o2_sensor_mv2_ = value_arg;
}


const int64_t* ProfileSample::o2_sensor_mv3() const {
  return o2_sensor_mv3_ ? &(*o2_sensor_mv3_) : nullptr;
}

void ProfileSample::set_o2_sensor_mv3(const int64_t* value_arg) {
  o2_sensor_mv3_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ProfileSample::set_o2_sensor_mv3(int64_t value_arg) {
  o2_sensor_mv3_ = value_arg;
}


const int64_t* ProfileSample::o2_sensor_mv4() const {
  return o2_sensor_mv4_ ? &(*o2_sensor_mv4_) : nullptr;
}

void ProfileSample::set_o2_sensor_mv4(const int64_t* value_arg) {
  o2_sensor_mv4_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ProfileSample::set_o2_sensor_mv4(int64_t value_arg) {
  o2_sensor_mv4_ = value_arg;
}


const int64_t* ProfileSample::o2_sensor_mv5() const {
  return o2_sensor_mv5_ ? &(*o2_sensor_mv5_) : nullptr;
}

void ProfileSample::set_o2_sensor_mv5(const int64_t* value_arg) {
  o2_sensor_mv5_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ProfileSample::set_o2_sensor_mv5(int64_t value_arg) {
  o2_sensor_mv5_ = value_arg;
}


const int64_t* ProfileSample::o2_sensor_mv6() const {
  return o2_sensor_mv6_ ? &(*o2_sensor_mv6_) : nullptr;
}

void ProfileSample::set_o2_sensor_mv6(const int64_t* value_arg) {
  o2_sensor_mv6_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ProfileSample::set_o2_sensor_mv6(int64_t value_arg) {
  o2_sensor_mv6_ = value_arg;
}


const int64_t* ProfileSample::gas_mix_index() const {
  return gas_mix_index_ ? &(*gas_mix_index_) : nullptr;
}

void ProfileSample::set_gas_mix_index(const int64_t* value_arg) {
  gas_mix_index_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ProfileSample::set_gas_mix_index(int64_t value_arg) {
  gas_mix_index_ = value_arg;
}


EncodableList ProfileSample::ToEncodableList() const {
  EncodableList list;
  list.reserve(29);
  list.push_back(EncodableValue(time_seconds_));
  list.push_back(EncodableValue(depth_meters_));
  list.push_back(temperature_celsius_ ? EncodableValue(*temperature_celsius_) : EncodableValue());
  list.push_back(pressure_bar_ ? EncodableValue(*pressure_bar_) : EncodableValue());
  list.push_back(tank_index_ ? EncodableValue(*tank_index_) : EncodableValue());
  list.push_back(tank_pressures_bar_ ? EncodableValue(*tank_pressures_bar_) : EncodableValue());
  list.push_back(heart_rate_ ? EncodableValue(*heart_rate_) : EncodableValue());
  list.push_back(heading_ ? EncodableValue(*heading_) : EncodableValue());
  list.push_back(setpoint_ ? EncodableValue(*setpoint_) : EncodableValue());
  list.push_back(ppo2_ ? EncodableValue(*ppo2_) : EncodableValue());
  list.push_back(cns_ ? EncodableValue(*cns_) : EncodableValue());
  list.push_back(rbt_ ? EncodableValue(*rbt_) : EncodableValue());
  list.push_back(deco_type_ ? EncodableValue(*deco_type_) : EncodableValue());
  list.push_back(deco_time_ ? EncodableValue(*deco_time_) : EncodableValue());
  list.push_back(deco_depth_ ? EncodableValue(*deco_depth_) : EncodableValue());
  list.push_back(tts_ ? EncodableValue(*tts_) : EncodableValue());
  list.push_back(o2_sensor1_ ? EncodableValue(*o2_sensor1_) : EncodableValue());
  list.push_back(o2_sensor2_ ? EncodableValue(*o2_sensor2_) : EncodableValue());
  list.push_back(o2_sensor3_ ? EncodableValue(*o2_sensor3_) : EncodableValue());
  list.push_back(o2_sensor4_ ? EncodableValue(*o2_sensor4_) : EncodableValue());
  list.push_back(o2_sensor5_ ? EncodableValue(*o2_sensor5_) : EncodableValue());
  list.push_back(o2_sensor6_ ? EncodableValue(*o2_sensor6_) : EncodableValue());
  list.push_back(o2_sensor_mv1_ ? EncodableValue(*o2_sensor_mv1_) : EncodableValue());
  list.push_back(o2_sensor_mv2_ ? EncodableValue(*o2_sensor_mv2_) : EncodableValue());
  list.push_back(o2_sensor_mv3_ ? EncodableValue(*o2_sensor_mv3_) : EncodableValue());
  list.push_back(o2_sensor_mv4_ ? EncodableValue(*o2_sensor_mv4_) : EncodableValue());
  list.push_back(o2_sensor_mv5_ ? EncodableValue(*o2_sensor_mv5_) : EncodableValue());
  list.push_back(o2_sensor_mv6_ ? EncodableValue(*o2_sensor_mv6_) : EncodableValue());
  list.push_back(gas_mix_index_ ? EncodableValue(*gas_mix_index_) : EncodableValue());
  return list;
}

ProfileSample ProfileSample::FromEncodableList(const EncodableList& list) {
  ProfileSample decoded(
    std::get<int64_t>(list[0]),
    std::get<double>(list[1]));
  auto& encodable_temperature_celsius = list[2];
  if (!encodable_temperature_celsius.IsNull()) {
    decoded.set_temperature_celsius(std::get<double>(encodable_temperature_celsius));
  }
  auto& encodable_pressure_bar = list[3];
  if (!encodable_pressure_bar.IsNull()) {
    decoded.set_pressure_bar(std::get<double>(encodable_pressure_bar));
  }
  auto& encodable_tank_index = list[4];
  if (!encodable_tank_index.IsNull()) {
    decoded.set_tank_index(std::get<int64_t>(encodable_tank_index));
  }
  auto& encodable_tank_pressures_bar = list[5];
  if (!encodable_tank_pressures_bar.IsNull()) {
    decoded.set_tank_pressures_bar(std::get<EncodableList>(encodable_tank_pressures_bar));
  }
  auto& encodable_heart_rate = list[6];
  if (!encodable_heart_rate.IsNull()) {
    decoded.set_heart_rate(std::get<int64_t>(encodable_heart_rate));
  }
  auto& encodable_heading = list[7];
  if (!encodable_heading.IsNull()) {
    decoded.set_heading(std::get<double>(encodable_heading));
  }
  auto& encodable_setpoint = list[8];
  if (!encodable_setpoint.IsNull()) {
    decoded.set_setpoint(std::get<double>(encodable_setpoint));
  }
  auto& encodable_ppo2 = list[9];
  if (!encodable_ppo2.IsNull()) {
    decoded.set_ppo2(std::get<double>(encodable_ppo2));
  }
  auto& encodable_cns = list[10];
  if (!encodable_cns.IsNull()) {
    decoded.set_cns(std::get<double>(encodable_cns));
  }
  auto& encodable_rbt = list[11];
  if (!encodable_rbt.IsNull()) {
    decoded.set_rbt(std::get<int64_t>(encodable_rbt));
  }
  auto& encodable_deco_type = list[12];
  if (!encodable_deco_type.IsNull()) {
    decoded.set_deco_type(std::get<int64_t>(encodable_deco_type));
  }
  auto& encodable_deco_time = list[13];
  if (!encodable_deco_time.IsNull()) {
    decoded.set_deco_time(std::get<int64_t>(encodable_deco_time));
  }
  auto& encodable_deco_depth = list[14];
  if (!encodable_deco_depth.IsNull()) {
    decoded.set_deco_depth(std::get<double>(encodable_deco_depth));
  }
  auto& encodable_tts = list[15];
  if (!encodable_tts.IsNull()) {
    decoded.set_tts(std::get<int64_t>(encodable_tts));
  }
  auto& encodable_o2_sensor1 = list[16];
  if (!encodable_o2_sensor1.IsNull()) {
    decoded.set_o2_sensor1(std::get<double>(encodable_o2_sensor1));
  }
  auto& encodable_o2_sensor2 = list[17];
  if (!encodable_o2_sensor2.IsNull()) {
    decoded.set_o2_sensor2(std::get<double>(encodable_o2_sensor2));
  }
  auto& encodable_o2_sensor3 = list[18];
  if (!encodable_o2_sensor3.IsNull()) {
    decoded.set_o2_sensor3(std::get<double>(encodable_o2_sensor3));
  }
  auto& encodable_o2_sensor4 = list[19];
  if (!encodable_o2_sensor4.IsNull()) {
    decoded.set_o2_sensor4(std::get<double>(encodable_o2_sensor4));
  }
  auto& encodable_o2_sensor5 = list[20];
  if (!encodable_o2_sensor5.IsNull()) {
    decoded.set_o2_sensor5(std::get<double>(encodable_o2_sensor5));
  }
  auto& encodable_o2_sensor6 = list[21];
  if (!encodable_o2_sensor6.IsNull()) {
    decoded.set_o2_sensor6(std::get<double>(encodable_o2_sensor6));
  }
  auto& encodable_o2_sensor_mv1 = list[22];
  if (!encodable_o2_sensor_mv1.IsNull()) {
    decoded.set_o2_sensor_mv1(std::get<int64_t>(encodable_o2_sensor_mv1));
  }
  auto& encodable_o2_sensor_mv2 = list[23];
  if (!encodable_o2_sensor_mv2.IsNull()) {
    decoded.set_o2_sensor_mv2(std::get<int64_t>(encodable_o2_sensor_mv2));
  }
  auto& encodable_o2_sensor_mv3 = list[24];
  if (!encodable_o2_sensor_mv3.IsNull()) {
    decoded.set_o2_sensor_mv3(std::get<int64_t>(encodable_o2_sensor_mv3));
  }
  auto& encodable_o2_sensor_mv4 = list[25];
  if (!encodable_o2_sensor_mv4.IsNull()) {
    decoded.set_o2_sensor_mv4(std::get<int64_t>(encodable_o2_sensor_mv4));
  }
  auto& encodable_o2_sensor_mv5 = list[26];
  if (!encodable_o2_sensor_mv5.IsNull()) {
    decoded.set_o2_sensor_mv5(std::get<int64_t>(encodable_o2_sensor_mv5));
  }
  auto& encodable_o2_sensor_mv6 = list[27];
  if (!encodable_o2_sensor_mv6.IsNull()) {
    decoded.set_o2_sensor_mv6(std::get<int64_t>(encodable_o2_sensor_mv6));
  }
  auto& encodable_gas_mix_index = list[28];
  if (!encodable_gas_mix_index.IsNull()) {
    decoded.set_gas_mix_index(std::get<int64_t>(encodable_gas_mix_index));
  }
  return decoded;
}

// GasMix

GasMix::GasMix(
  int64_t index,
  double o2_percent,
  double he_percent)
 : index_(index),
    o2_percent_(o2_percent),
    he_percent_(he_percent) {}

int64_t GasMix::index() const {
  return index_;
}

void GasMix::set_index(int64_t value_arg) {
  index_ = value_arg;
}


double GasMix::o2_percent() const {
  return o2_percent_;
}

void GasMix::set_o2_percent(double value_arg) {
  o2_percent_ = value_arg;
}


double GasMix::he_percent() const {
  return he_percent_;
}

void GasMix::set_he_percent(double value_arg) {
  he_percent_ = value_arg;
}


EncodableList GasMix::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(index_));
  list.push_back(EncodableValue(o2_percent_));
  list.push_back(EncodableValue(he_percent_));
  return list;
}

GasMix GasMix::FromEncodableList(const EncodableList& list) {
  GasMix decoded(
    std::get<int64_t>(list[0]),
    std::get<double>(list[1]),
    std::get<double>(list[2]));
  return decoded;
}

// TankInfo

TankInfo::TankInfo(
  int64_t index,
  int64_t gas_mix_index)
 : index_(index),
    gas_mix_index_(gas_mix_index) {}

TankInfo::TankInfo(
  int64_t index,
  int64_t gas_mix_index,
  const double* volume_liters,
  const double* start_pressure_bar,
  const double* end_pressure_bar,
  const int64_t* usage,
  const int64_t* transmitter_serial)
 : index_(index),
    gas_mix_index_(gas_mix_index),
    volume_liters_(volume_liters ? std::optional<double>(*volume_liters) : std::nullopt),
    start_pressure_bar_(start_pressure_bar ? std::optional<double>(*start_pressure_bar) : std::nullopt),
    end_pressure_bar_(end_pressure_bar ? std::optional<double>(*end_pressure_bar) : std::nullopt),
    usage_(usage ? std::optional<int64_t>(*usage) : std::nullopt),
    transmitter_serial_(transmitter_serial ? std::optional<int64_t>(*transmitter_serial) : std::nullopt) {}

int64_t TankInfo::index() const {
  return index_;
}

void TankInfo::set_index(int64_t value_arg) {
  index_ = value_arg;
}


int64_t TankInfo::gas_mix_index() const {
  return gas_mix_index_;
}

void TankInfo::set_gas_mix_index(int64_t value_arg) {
  gas_mix_index_ = value_arg;
}


const double* TankInfo::volume_liters() const {
  return volume_liters_ ? &(*volume_liters_) : nullptr;
}

void TankInfo::set_volume_liters(const double* value_arg) {
  volume_liters_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void TankInfo::set_volume_liters(double value_arg) {
  volume_liters_ = value_arg;
}


const double* TankInfo::start_pressure_bar() const {
  return start_pressure_bar_ ? &(*start_pressure_bar_) : nullptr;
}

void TankInfo::set_start_pressure_bar(const double* value_arg) {
  start_pressure_bar_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void TankInfo::set_start_pressure_bar(double value_arg) {
  start_pressure_bar_ = value_arg;
}


const double* TankInfo::end_pressure_bar() const {
  return end_pressure_bar_ ? &(*end_pressure_bar_) : nullptr;
}

void TankInfo::set_end_pressure_bar(const double* value_arg) {
  end_pressure_bar_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void TankInfo::set_end_pressure_bar(double value_arg) {
  end_pressure_bar_ = value_arg;
}


const int64_t* TankInfo::usage() const {
  return usage_ ? &(*usage_) : nullptr;
}

void TankInfo::set_usage(const int64_t* value_arg) {
  usage_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void TankInfo::set_usage(int64_t value_arg) {
  usage_ = value_arg;
}


const int64_t* TankInfo::transmitter_serial() const {
  return transmitter_serial_ ? &(*transmitter_serial_) : nullptr;
}

void TankInfo::set_transmitter_serial(const int64_t* value_arg) {
  transmitter_serial_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void TankInfo::set_transmitter_serial(int64_t value_arg) {
  transmitter_serial_ = value_arg;
}


EncodableList TankInfo::ToEncodableList() const {
  EncodableList list;
  list.reserve(7);
  list.push_back(EncodableValue(index_));
  list.push_back(EncodableValue(gas_mix_index_));
  list.push_back(volume_liters_ ? EncodableValue(*volume_liters_) : EncodableValue());
  list.push_back(start_pressure_bar_ ? EncodableValue(*start_pressure_bar_) : EncodableValue());
  list.push_back(end_pressure_bar_ ? EncodableValue(*end_pressure_bar_) : EncodableValue());
  list.push_back(usage_ ? EncodableValue(*usage_) : EncodableValue());
  list.push_back(transmitter_serial_ ? EncodableValue(*transmitter_serial_) : EncodableValue());
  return list;
}

TankInfo TankInfo::FromEncodableList(const EncodableList& list) {
  TankInfo decoded(
    std::get<int64_t>(list[0]),
    std::get<int64_t>(list[1]));
  auto& encodable_volume_liters = list[2];
  if (!encodable_volume_liters.IsNull()) {
    decoded.set_volume_liters(std::get<double>(encodable_volume_liters));
  }
  auto& encodable_start_pressure_bar = list[3];
  if (!encodable_start_pressure_bar.IsNull()) {
    decoded.set_start_pressure_bar(std::get<double>(encodable_start_pressure_bar));
  }
  auto& encodable_end_pressure_bar = list[4];
  if (!encodable_end_pressure_bar.IsNull()) {
    decoded.set_end_pressure_bar(std::get<double>(encodable_end_pressure_bar));
  }
  auto& encodable_usage = list[5];
  if (!encodable_usage.IsNull()) {
    decoded.set_usage(std::get<int64_t>(encodable_usage));
  }
  auto& encodable_transmitter_serial = list[6];
  if (!encodable_transmitter_serial.IsNull()) {
    decoded.set_transmitter_serial(std::get<int64_t>(encodable_transmitter_serial));
  }
  return decoded;
}

// DiveEvent

DiveEvent::DiveEvent(
  int64_t time_seconds,
  const std::string& type)
 : time_seconds_(time_seconds),
    type_(type) {}

DiveEvent::DiveEvent(
  int64_t time_seconds,
  const std::string& type,
  const EncodableMap* data)
 : time_seconds_(time_seconds),
    type_(type),
    data_(data ? std::optional<EncodableMap>(*data) : std::nullopt) {}

int64_t DiveEvent::time_seconds() const {
  return time_seconds_;
}

void DiveEvent::set_time_seconds(int64_t value_arg) {
  time_seconds_ = value_arg;
}


const std::string& DiveEvent::type() const {
  return type_;
}

void DiveEvent::set_type(std::string_view value_arg) {
  type_ = value_arg;
}


const EncodableMap* DiveEvent::data() const {
  return data_ ? &(*data_) : nullptr;
}

void DiveEvent::set_data(const EncodableMap* value_arg) {
  data_ = value_arg ? std::optional<EncodableMap>(*value_arg) : std::nullopt;
}

void DiveEvent::set_data(const EncodableMap& value_arg) {
  data_ = value_arg;
}


EncodableList DiveEvent::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(time_seconds_));
  list.push_back(EncodableValue(type_));
  list.push_back(data_ ? EncodableValue(*data_) : EncodableValue());
  return list;
}

DiveEvent DiveEvent::FromEncodableList(const EncodableList& list) {
  DiveEvent decoded(
    std::get<int64_t>(list[0]),
    std::get<std::string>(list[1]));
  auto& encodable_data = list[2];
  if (!encodable_data.IsNull()) {
    decoded.set_data(std::get<EncodableMap>(encodable_data));
  }
  return decoded;
}

// ParsedDive

ParsedDive::ParsedDive(
  const std::string& fingerprint,
  int64_t date_time_year,
  int64_t date_time_month,
  int64_t date_time_day,
  int64_t date_time_hour,
  int64_t date_time_minute,
  int64_t date_time_second,
  double max_depth_meters,
  double avg_depth_meters,
  int64_t duration_seconds,
  const EncodableList& samples,
  const EncodableList& tanks,
  const EncodableList& gas_mixes,
  const EncodableList& events)
 : fingerprint_(fingerprint),
    date_time_year_(date_time_year),
    date_time_month_(date_time_month),
    date_time_day_(date_time_day),
    date_time_hour_(date_time_hour),
    date_time_minute_(date_time_minute),
    date_time_second_(date_time_second),
    max_depth_meters_(max_depth_meters),
    avg_depth_meters_(avg_depth_meters),
    duration_seconds_(duration_seconds),
    samples_(samples),
    tanks_(tanks),
    gas_mixes_(gas_mixes),
    events_(events) {}

ParsedDive::ParsedDive(
  const std::string& fingerprint,
  int64_t date_time_year,
  int64_t date_time_month,
  int64_t date_time_day,
  int64_t date_time_hour,
  int64_t date_time_minute,
  int64_t date_time_second,
  const int64_t* date_time_timezone_offset,
  double max_depth_meters,
  double avg_depth_meters,
  int64_t duration_seconds,
  const double* min_temperature_celsius,
  const double* max_temperature_celsius,
  const EncodableList& samples,
  const EncodableList& tanks,
  const EncodableList& gas_mixes,
  const EncodableList& events,
  const std::string* dive_mode,
  const std::string* deco_algorithm,
  const int64_t* gf_low,
  const int64_t* gf_high,
  const int64_t* deco_conservatism,
  const std::vector<uint8_t>* raw_data,
  const std::vector<uint8_t>* raw_fingerprint,
  const double* entry_latitude,
  const double* entry_longitude,
  const double* exit_latitude,
  const double* exit_longitude,
  const double* ppo2_max_bar)
 : fingerprint_(fingerprint),
    date_time_year_(date_time_year),
    date_time_month_(date_time_month),
    date_time_day_(date_time_day),
    date_time_hour_(date_time_hour),
    date_time_minute_(date_time_minute),
    date_time_second_(date_time_second),
    date_time_timezone_offset_(date_time_timezone_offset ? std::optional<int64_t>(*date_time_timezone_offset) : std::nullopt),
    max_depth_meters_(max_depth_meters),
    avg_depth_meters_(avg_depth_meters),
    duration_seconds_(duration_seconds),
    min_temperature_celsius_(min_temperature_celsius ? std::optional<double>(*min_temperature_celsius) : std::nullopt),
    max_temperature_celsius_(max_temperature_celsius ? std::optional<double>(*max_temperature_celsius) : std::nullopt),
    samples_(samples),
    tanks_(tanks),
    gas_mixes_(gas_mixes),
    events_(events),
    dive_mode_(dive_mode ? std::optional<std::string>(*dive_mode) : std::nullopt),
    deco_algorithm_(deco_algorithm ? std::optional<std::string>(*deco_algorithm) : std::nullopt),
    gf_low_(gf_low ? std::optional<int64_t>(*gf_low) : std::nullopt),
    gf_high_(gf_high ? std::optional<int64_t>(*gf_high) : std::nullopt),
    deco_conservatism_(deco_conservatism ? std::optional<int64_t>(*deco_conservatism) : std::nullopt),
    raw_data_(raw_data ? std::optional<std::vector<uint8_t>>(*raw_data) : std::nullopt),
    raw_fingerprint_(raw_fingerprint ? std::optional<std::vector<uint8_t>>(*raw_fingerprint) : std::nullopt),
    entry_latitude_(entry_latitude ? std::optional<double>(*entry_latitude) : std::nullopt),
    entry_longitude_(entry_longitude ? std::optional<double>(*entry_longitude) : std::nullopt),
    exit_latitude_(exit_latitude ? std::optional<double>(*exit_latitude) : std::nullopt),
    exit_longitude_(exit_longitude ? std::optional<double>(*exit_longitude) : std::nullopt),
    ppo2_max_bar_(ppo2_max_bar ? std::optional<double>(*ppo2_max_bar) : std::nullopt) {}

const std::string& ParsedDive::fingerprint() const {
  return fingerprint_;
}

void ParsedDive::set_fingerprint(std::string_view value_arg) {
  fingerprint_ = value_arg;
}


int64_t ParsedDive::date_time_year() const {
  return date_time_year_;
}

void ParsedDive::set_date_time_year(int64_t value_arg) {
  date_time_year_ = value_arg;
}


int64_t ParsedDive::date_time_month() const {
  return date_time_month_;
}

void ParsedDive::set_date_time_month(int64_t value_arg) {
  date_time_month_ = value_arg;
}


int64_t ParsedDive::date_time_day() const {
  return date_time_day_;
}

void ParsedDive::set_date_time_day(int64_t value_arg) {
  date_time_day_ = value_arg;
}


int64_t ParsedDive::date_time_hour() const {
  return date_time_hour_;
}

void ParsedDive::set_date_time_hour(int64_t value_arg) {
  date_time_hour_ = value_arg;
}


int64_t ParsedDive::date_time_minute() const {
  return date_time_minute_;
}

void ParsedDive::set_date_time_minute(int64_t value_arg) {
  date_time_minute_ = value_arg;
}


int64_t ParsedDive::date_time_second() const {
  return date_time_second_;
}

void ParsedDive::set_date_time_second(int64_t value_arg) {
  date_time_second_ = value_arg;
}


const int64_t* ParsedDive::date_time_timezone_offset() const {
  return date_time_timezone_offset_ ? &(*date_time_timezone_offset_) : nullptr;
}

void ParsedDive::set_date_time_timezone_offset(const int64_t* value_arg) {
  date_time_timezone_offset_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ParsedDive::set_date_time_timezone_offset(int64_t value_arg) {
  date_time_timezone_offset_ = value_arg;
}


double ParsedDive::max_depth_meters() const {
  return max_depth_meters_;
}

void ParsedDive::set_max_depth_meters(double value_arg) {
  max_depth_meters_ = value_arg;
}


double ParsedDive::avg_depth_meters() const {
  return avg_depth_meters_;
}

void ParsedDive::set_avg_depth_meters(double value_arg) {
  avg_depth_meters_ = value_arg;
}


int64_t ParsedDive::duration_seconds() const {
  return duration_seconds_;
}

void ParsedDive::set_duration_seconds(int64_t value_arg) {
  duration_seconds_ = value_arg;
}


const double* ParsedDive::min_temperature_celsius() const {
  return min_temperature_celsius_ ? &(*min_temperature_celsius_) : nullptr;
}

void ParsedDive::set_min_temperature_celsius(const double* value_arg) {
  min_temperature_celsius_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ParsedDive::set_min_temperature_celsius(double value_arg) {
  min_temperature_celsius_ = value_arg;
}


const double* ParsedDive::max_temperature_celsius() const {
  return max_temperature_celsius_ ? &(*max_temperature_celsius_) : nullptr;
}

void ParsedDive::set_max_temperature_celsius(const double* value_arg) {
  max_temperature_celsius_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ParsedDive::set_max_temperature_celsius(double value_arg) {
  max_temperature_celsius_ = value_arg;
}


const EncodableList& ParsedDive::samples() const {
  return samples_;
}

void ParsedDive::set_samples(const EncodableList& value_arg) {
  samples_ = value_arg;
}


const EncodableList& ParsedDive::tanks() const {
  return tanks_;
}

void ParsedDive::set_tanks(const EncodableList& value_arg) {
  tanks_ = value_arg;
}


const EncodableList& ParsedDive::gas_mixes() const {
  return gas_mixes_;
}

void ParsedDive::set_gas_mixes(const EncodableList& value_arg) {
  gas_mixes_ = value_arg;
}


const EncodableList& ParsedDive::events() const {
  return events_;
}

void ParsedDive::set_events(const EncodableList& value_arg) {
  events_ = value_arg;
}


const std::string* ParsedDive::dive_mode() const {
  return dive_mode_ ? &(*dive_mode_) : nullptr;
}

void ParsedDive::set_dive_mode(const std::string_view* value_arg) {
  dive_mode_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void ParsedDive::set_dive_mode(std::string_view value_arg) {
  dive_mode_ = value_arg;
}


const std::string* ParsedDive::deco_algorithm() const {
  return deco_algorithm_ ? &(*deco_algorithm_) : nullptr;
}

void ParsedDive::set_deco_algorithm(const std::string_view* value_arg) {
  deco_algorithm_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void ParsedDive::set_deco_algorithm(std::string_view value_arg) {
  deco_algorithm_ = value_arg;
}


const int64_t* ParsedDive::gf_low() const {
  return gf_low_ ? &(*gf_low_) : nullptr;
}

void ParsedDive::set_gf_low(const int64_t* value_arg) {
  gf_low_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ParsedDive::set_gf_low(int64_t value_arg) {
  gf_low_ = value_arg;
}


const int64_t* ParsedDive::gf_high() const {
  return gf_high_ ? &(*gf_high_) : nullptr;
}

void ParsedDive::set_gf_high(const int64_t* value_arg) {
  gf_high_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ParsedDive::set_gf_high(int64_t value_arg) {
  gf_high_ = value_arg;
}


const int64_t* ParsedDive::deco_conservatism() const {
  return deco_conservatism_ ? &(*deco_conservatism_) : nullptr;
}

void ParsedDive::set_deco_conservatism(const int64_t* value_arg) {
  deco_conservatism_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void ParsedDive::set_deco_conservatism(int64_t value_arg) {
  deco_conservatism_ = value_arg;
}


const std::vector<uint8_t>* ParsedDive::raw_data() const {
  return raw_data_ ? &(*raw_data_) : nullptr;
}

void ParsedDive::set_raw_data(const std::vector<uint8_t>* value_arg) {
  raw_data_ = value_arg ? std::optional<std::vector<uint8_t>>(*value_arg) : std::nullopt;
}

void ParsedDive::set_raw_data(const std::vector<uint8_t>& value_arg) {
  raw_data_ = value_arg;
}


const std::vector<uint8_t>* ParsedDive::raw_fingerprint() const {
  return raw_fingerprint_ ? &(*raw_fingerprint_) : nullptr;
}

void ParsedDive::set_raw_fingerprint(const std::vector<uint8_t>* value_arg) {
  raw_fingerprint_ = value_arg ? std::optional<std::vector<uint8_t>>(*value_arg) : std::nullopt;
}

void ParsedDive::set_raw_fingerprint(const std::vector<uint8_t>& value_arg) {
  raw_fingerprint_ = value_arg;
}


const double* ParsedDive::entry_latitude() const {
  return entry_latitude_ ? &(*entry_latitude_) : nullptr;
}

void ParsedDive::set_entry_latitude(const double* value_arg) {
  entry_latitude_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ParsedDive::set_entry_latitude(double value_arg) {
  entry_latitude_ = value_arg;
}


const double* ParsedDive::entry_longitude() const {
  return entry_longitude_ ? &(*entry_longitude_) : nullptr;
}

void ParsedDive::set_entry_longitude(const double* value_arg) {
  entry_longitude_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ParsedDive::set_entry_longitude(double value_arg) {
  entry_longitude_ = value_arg;
}


const double* ParsedDive::exit_latitude() const {
  return exit_latitude_ ? &(*exit_latitude_) : nullptr;
}

void ParsedDive::set_exit_latitude(const double* value_arg) {
  exit_latitude_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ParsedDive::set_exit_latitude(double value_arg) {
  exit_latitude_ = value_arg;
}


const double* ParsedDive::exit_longitude() const {
  return exit_longitude_ ? &(*exit_longitude_) : nullptr;
}

void ParsedDive::set_exit_longitude(const double* value_arg) {
  exit_longitude_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ParsedDive::set_exit_longitude(double value_arg) {
  exit_longitude_ = value_arg;
}

const double* ParsedDive::ppo2_max_bar() const {
  return ppo2_max_bar_ ? &(*ppo2_max_bar_) : nullptr;
}

void ParsedDive::set_ppo2_max_bar(const double* value_arg) {
  ppo2_max_bar_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void ParsedDive::set_ppo2_max_bar(double value_arg) {
  ppo2_max_bar_ = value_arg;
}


EncodableList ParsedDive::ToEncodableList() const {
  EncodableList list;
  list.reserve(29);
  list.push_back(EncodableValue(fingerprint_));
  list.push_back(EncodableValue(date_time_year_));
  list.push_back(EncodableValue(date_time_month_));
  list.push_back(EncodableValue(date_time_day_));
  list.push_back(EncodableValue(date_time_hour_));
  list.push_back(EncodableValue(date_time_minute_));
  list.push_back(EncodableValue(date_time_second_));
  list.push_back(date_time_timezone_offset_ ? EncodableValue(*date_time_timezone_offset_) : EncodableValue());
  list.push_back(EncodableValue(max_depth_meters_));
  list.push_back(EncodableValue(avg_depth_meters_));
  list.push_back(EncodableValue(duration_seconds_));
  list.push_back(min_temperature_celsius_ ? EncodableValue(*min_temperature_celsius_) : EncodableValue());
  list.push_back(max_temperature_celsius_ ? EncodableValue(*max_temperature_celsius_) : EncodableValue());
  list.push_back(EncodableValue(samples_));
  list.push_back(EncodableValue(tanks_));
  list.push_back(EncodableValue(gas_mixes_));
  list.push_back(EncodableValue(events_));
  list.push_back(dive_mode_ ? EncodableValue(*dive_mode_) : EncodableValue());
  list.push_back(deco_algorithm_ ? EncodableValue(*deco_algorithm_) : EncodableValue());
  list.push_back(gf_low_ ? EncodableValue(*gf_low_) : EncodableValue());
  list.push_back(gf_high_ ? EncodableValue(*gf_high_) : EncodableValue());
  list.push_back(deco_conservatism_ ? EncodableValue(*deco_conservatism_) : EncodableValue());
  list.push_back(raw_data_ ? EncodableValue(*raw_data_) : EncodableValue());
  list.push_back(raw_fingerprint_ ? EncodableValue(*raw_fingerprint_) : EncodableValue());
  list.push_back(entry_latitude_ ? EncodableValue(*entry_latitude_) : EncodableValue());
  list.push_back(entry_longitude_ ? EncodableValue(*entry_longitude_) : EncodableValue());
  list.push_back(exit_latitude_ ? EncodableValue(*exit_latitude_) : EncodableValue());
  list.push_back(exit_longitude_ ? EncodableValue(*exit_longitude_) : EncodableValue());
  list.push_back(ppo2_max_bar_ ? EncodableValue(*ppo2_max_bar_) : EncodableValue());
  return list;
}

ParsedDive ParsedDive::FromEncodableList(const EncodableList& list) {
  ParsedDive decoded(
    std::get<std::string>(list[0]),
    std::get<int64_t>(list[1]),
    std::get<int64_t>(list[2]),
    std::get<int64_t>(list[3]),
    std::get<int64_t>(list[4]),
    std::get<int64_t>(list[5]),
    std::get<int64_t>(list[6]),
    std::get<double>(list[8]),
    std::get<double>(list[9]),
    std::get<int64_t>(list[10]),
    std::get<EncodableList>(list[13]),
    std::get<EncodableList>(list[14]),
    std::get<EncodableList>(list[15]),
    std::get<EncodableList>(list[16]));
  auto& encodable_date_time_timezone_offset = list[7];
  if (!encodable_date_time_timezone_offset.IsNull()) {
    decoded.set_date_time_timezone_offset(std::get<int64_t>(encodable_date_time_timezone_offset));
  }
  auto& encodable_min_temperature_celsius = list[11];
  if (!encodable_min_temperature_celsius.IsNull()) {
    decoded.set_min_temperature_celsius(std::get<double>(encodable_min_temperature_celsius));
  }
  auto& encodable_max_temperature_celsius = list[12];
  if (!encodable_max_temperature_celsius.IsNull()) {
    decoded.set_max_temperature_celsius(std::get<double>(encodable_max_temperature_celsius));
  }
  auto& encodable_dive_mode = list[17];
  if (!encodable_dive_mode.IsNull()) {
    decoded.set_dive_mode(std::get<std::string>(encodable_dive_mode));
  }
  auto& encodable_deco_algorithm = list[18];
  if (!encodable_deco_algorithm.IsNull()) {
    decoded.set_deco_algorithm(std::get<std::string>(encodable_deco_algorithm));
  }
  auto& encodable_gf_low = list[19];
  if (!encodable_gf_low.IsNull()) {
    decoded.set_gf_low(std::get<int64_t>(encodable_gf_low));
  }
  auto& encodable_gf_high = list[20];
  if (!encodable_gf_high.IsNull()) {
    decoded.set_gf_high(std::get<int64_t>(encodable_gf_high));
  }
  auto& encodable_deco_conservatism = list[21];
  if (!encodable_deco_conservatism.IsNull()) {
    decoded.set_deco_conservatism(std::get<int64_t>(encodable_deco_conservatism));
  }
  auto& encodable_raw_data = list[22];
  if (!encodable_raw_data.IsNull()) {
    decoded.set_raw_data(std::get<std::vector<uint8_t>>(encodable_raw_data));
  }
  auto& encodable_raw_fingerprint = list[23];
  if (!encodable_raw_fingerprint.IsNull()) {
    decoded.set_raw_fingerprint(std::get<std::vector<uint8_t>>(encodable_raw_fingerprint));
  }
  auto& encodable_entry_latitude = list[24];
  if (!encodable_entry_latitude.IsNull()) {
    decoded.set_entry_latitude(std::get<double>(encodable_entry_latitude));
  }
  auto& encodable_entry_longitude = list[25];
  if (!encodable_entry_longitude.IsNull()) {
    decoded.set_entry_longitude(std::get<double>(encodable_entry_longitude));
  }
  auto& encodable_exit_latitude = list[26];
  if (!encodable_exit_latitude.IsNull()) {
    decoded.set_exit_latitude(std::get<double>(encodable_exit_latitude));
  }
  auto& encodable_exit_longitude = list[27];
  if (!encodable_exit_longitude.IsNull()) {
    decoded.set_exit_longitude(std::get<double>(encodable_exit_longitude));
  }
  auto& encodable_ppo2_max_bar = list[28];
  if (!encodable_ppo2_max_bar.IsNull()) {
    decoded.set_ppo2_max_bar(std::get<double>(encodable_ppo2_max_bar));
  }
  return decoded;
}

// DownloadProgress

DownloadProgress::DownloadProgress(
  int64_t current,
  int64_t total,
  const std::string& status)
 : current_(current),
    total_(total),
    status_(status) {}

int64_t DownloadProgress::current() const {
  return current_;
}

void DownloadProgress::set_current(int64_t value_arg) {
  current_ = value_arg;
}


int64_t DownloadProgress::total() const {
  return total_;
}

void DownloadProgress::set_total(int64_t value_arg) {
  total_ = value_arg;
}


const std::string& DownloadProgress::status() const {
  return status_;
}

void DownloadProgress::set_status(std::string_view value_arg) {
  status_ = value_arg;
}


EncodableList DownloadProgress::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(current_));
  list.push_back(EncodableValue(total_));
  list.push_back(EncodableValue(status_));
  return list;
}

DownloadProgress DownloadProgress::FromEncodableList(const EncodableList& list) {
  DownloadProgress decoded(
    std::get<int64_t>(list[0]),
    std::get<int64_t>(list[1]),
    std::get<std::string>(list[2]));
  return decoded;
}

// DiveComputerError

DiveComputerError::DiveComputerError(
  const std::string& code,
  const std::string& message)
 : code_(code),
    message_(message) {}

const std::string& DiveComputerError::code() const {
  return code_;
}

void DiveComputerError::set_code(std::string_view value_arg) {
  code_ = value_arg;
}


const std::string& DiveComputerError::message() const {
  return message_;
}

void DiveComputerError::set_message(std::string_view value_arg) {
  message_ = value_arg;
}


EncodableList DiveComputerError::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(code_));
  list.push_back(EncodableValue(message_));
  return list;
}

DiveComputerError DiveComputerError::FromEncodableList(const EncodableList& list) {
  DiveComputerError decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]));
  return decoded;
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<TransportType>(enum_arg_value));
      }
    case 130: {
        return CustomEncodableValue(DeviceDescriptor::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 131: {
        return CustomEncodableValue(DiscoveredDevice::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 132: {
        return CustomEncodableValue(ProfileSample::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 133: {
        return CustomEncodableValue(GasMix::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 134: {
        return CustomEncodableValue(TankInfo::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 135: {
        return CustomEncodableValue(DiveEvent::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 136: {
        return CustomEncodableValue(ParsedDive::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 137: {
        return CustomEncodableValue(DownloadProgress::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 138: {
        return CustomEncodableValue(DiveComputerError::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(TransportType)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<TransportType>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(DeviceDescriptor)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(std::any_cast<DeviceDescriptor>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(DiscoveredDevice)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<DiscoveredDevice>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(ProfileSample)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(std::any_cast<ProfileSample>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(GasMix)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(std::any_cast<GasMix>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(TankInfo)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(std::any_cast<TankInfo>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(DiveEvent)) {
      stream->WriteByte(135);
      WriteValue(EncodableValue(std::any_cast<DiveEvent>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(ParsedDive)) {
      stream->WriteByte(136);
      WriteValue(EncodableValue(std::any_cast<ParsedDive>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(DownloadProgress)) {
      stream->WriteByte(137);
      WriteValue(EncodableValue(std::any_cast<DownloadProgress>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(DiveComputerError)) {
      stream->WriteByte(138);
      WriteValue(EncodableValue(std::any_cast<DiveComputerError>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by DiveComputerHostApi.
const flutter::StandardMessageCodec& DiveComputerHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `DiveComputerHostApi` to handle messages through the `binary_messenger`.
void DiveComputerHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  DiveComputerHostApi* api) {
  DiveComputerHostApi::SetUp(binary_messenger, api, "");
}

void DiveComputerHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  DiveComputerHostApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.getDeviceDescriptors" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->GetDeviceDescriptors([reply](ErrorOr<EncodableList>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.startDiscovery" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_transport_arg = args.at(0);
          if (encodable_transport_arg.IsNull()) {
            reply(WrapError("transport_arg unexpectedly null."));
            return;
          }
          const auto& transport_arg = std::any_cast<const TransportType&>(std::get<CustomEncodableValue>(encodable_transport_arg));
          api->StartDiscovery(transport_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.stopDiscovery" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->StopDiscovery();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.startDownload" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_device_arg = args.at(0);
          if (encodable_device_arg.IsNull()) {
            reply(WrapError("device_arg unexpectedly null."));
            return;
          }
          const auto& device_arg = std::any_cast<const DiscoveredDevice&>(std::get<CustomEncodableValue>(encodable_device_arg));
          const auto& encodable_fingerprint_arg = args.at(1);
          const auto* fingerprint_arg = std::get_if<std::string>(&encodable_fingerprint_arg);
          api->StartDownload(device_arg, fingerprint_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.cancelDownload" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          std::optional<FlutterError> output = api->CancelDownload();
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.submitPinCode" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_pin_code_arg = args.at(0);
          if (encodable_pin_code_arg.IsNull()) {
            reply(WrapError("pin_code_arg unexpectedly null."));
            return;
          }
          const auto& pin_code_arg = std::get<std::string>(encodable_pin_code_arg);
          std::optional<FlutterError> output = api->SubmitPinCode(pin_code_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.getLibdivecomputerVersion" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          ErrorOr<std::string> output = api->GetLibdivecomputerVersion();
          if (output.has_error()) {
            reply(WrapError(output.error()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.parseRawDiveData" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_vendor_arg = args.at(0);
          if (encodable_vendor_arg.IsNull()) {
            reply(WrapError("vendor_arg unexpectedly null."));
            return;
          }
          const auto& vendor_arg = std::get<std::string>(encodable_vendor_arg);
          const auto& encodable_product_arg = args.at(1);
          if (encodable_product_arg.IsNull()) {
            reply(WrapError("product_arg unexpectedly null."));
            return;
          }
          const auto& product_arg = std::get<std::string>(encodable_product_arg);
          const auto& encodable_model_arg = args.at(2);
          if (encodable_model_arg.IsNull()) {
            reply(WrapError("model_arg unexpectedly null."));
            return;
          }
          const int64_t model_arg = encodable_model_arg.LongValue();
          const auto& encodable_data_arg = args.at(3);
          if (encodable_data_arg.IsNull()) {
            reply(WrapError("data_arg unexpectedly null."));
            return;
          }
          const auto& data_arg = std::get<std::vector<uint8_t>>(encodable_data_arg);
          api->ParseRawDiveData(vendor_arg, product_arg, model_arg, data_arg, [reply](ErrorOr<ParsedDive>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue DiveComputerHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue DiveComputerHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
DiveComputerFlutterApi::DiveComputerFlutterApi(flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_("") {}

DiveComputerFlutterApi::DiveComputerFlutterApi(
  flutter::BinaryMessenger* binary_messenger,
  const std::string& message_channel_suffix)
 : binary_messenger_(binary_messenger),
    message_channel_suffix_(message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "") {}

const flutter::StandardMessageCodec& DiveComputerFlutterApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

void DiveComputerFlutterApi::OnDeviceDiscovered(
  const DiscoveredDevice& device_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onDeviceDiscovered" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(device_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void DiveComputerFlutterApi::OnDiscoveryComplete(
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onDiscoveryComplete" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue();
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void DiveComputerFlutterApi::OnDownloadProgress(
  const DownloadProgress& progress_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onDownloadProgress" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(progress_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void DiveComputerFlutterApi::OnDiveDownloaded(
  const ParsedDive& dive_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onDiveDownloaded" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(dive_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void DiveComputerFlutterApi::OnDownloadComplete(
  int64_t total_dives_arg,
  const std::string* serial_number_arg,
  const std::string* firmware_version_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onDownloadComplete" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(total_dives_arg),
    serial_number_arg ? EncodableValue(*serial_number_arg) : EncodableValue(),
    firmware_version_arg ? EncodableValue(*firmware_version_arg) : EncodableValue(),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void DiveComputerFlutterApi::OnError(
  const DiveComputerError& error_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onError" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    CustomEncodableValue(error_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void DiveComputerFlutterApi::OnPinCodeRequired(
  const std::string& device_address_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onPinCodeRequired" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(device_address_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

void DiveComputerFlutterApi::OnLogEvent(
  const std::string& category_arg,
  const std::string& level_arg,
  const std::string& message_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onLogEvent" + message_channel_suffix_;
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(category_arg),
    EncodableValue(level_arg),
    EncodableValue(message_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

}  // namespace libdivecomputer_plugin
