// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_DIVE_COMPUTER_API_G_H_
#define PIGEON_DIVE_COMPUTER_API_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace libdivecomputer_plugin {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class DiveComputerHostApi;
  friend class DiveComputerFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class TransportType {
  kBle = 0,
  kUsb = 1,
  kSerial = 2,
  kInfrared = 3
};


// Generated class from Pigeon that represents data sent in messages.
class DeviceDescriptor {
 public:
  // Constructs an object setting all fields.
  explicit DeviceDescriptor(
    const std::string& vendor,
    const std::string& product,
    int64_t model,
    const flutter::EncodableList& transports);

  const std::string& vendor() const;
  void set_vendor(std::string_view value_arg);

  const std::string& product() const;
  void set_product(std::string_view value_arg);

  int64_t model() const;
  void set_model(int64_t value_arg);

  const flutter::EncodableList& transports() const;
  void set_transports(const flutter::EncodableList& value_arg);


 private:
  static DeviceDescriptor FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class DiveComputerHostApi;
  friend class DiveComputerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string vendor_;
  std::string product_;
  int64_t model_;
  flutter::EncodableList transports_;

};


// Generated class from Pigeon that represents data sent in messages.
class DiscoveredDevice {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit DiscoveredDevice(
    const std::string& vendor,
    const std::string& product,
    int64_t model,
    const std::string& address,
    const TransportType& transport);

  // Constructs an object setting all fields.
  explicit DiscoveredDevice(
    const std::string& vendor,
    const std::string& product,
    int64_t model,
    const std::string& address,
    const std::string* name,
    const TransportType& transport);

  const std::string& vendor() const;
  void set_vendor(std::string_view value_arg);

  const std::string& product() const;
  void set_product(std::string_view value_arg);

  int64_t model() const;
  void set_model(int64_t value_arg);

  const std::string& address() const;
  void set_address(std::string_view value_arg);

  const std::string* name() const;
  void set_name(const std::string_view* value_arg);
  void set_name(std::string_view value_arg);

  const TransportType& transport() const;
  void set_transport(const TransportType& value_arg);


 private:
  static DiscoveredDevice FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class DiveComputerHostApi;
  friend class DiveComputerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string vendor_;
  std::string product_;
  int64_t model_;
  std::string address_;
  std::optional<std::string> name_;
  TransportType transport_;

};


// Generated class from Pigeon that represents data sent in messages.
class ProfileSample {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit ProfileSample(
    int64_t time_seconds,
    double depth_meters);

  // Constructs an object setting all fields.
  explicit ProfileSample(
    int64_t time_seconds,
    double depth_meters,
    const double* temperature_celsius,
    const double* pressure_bar,
    const int64_t* tank_index,
    const flutter::EncodableList* tank_pressures_bar,
    const int64_t* heart_rate,
    const double* heading,
    const double* setpoint,
    const double* ppo2,
    const double* cns,
    const int64_t* rbt,
    const int64_t* deco_type,
    const int64_t* deco_time,
    const double* deco_depth,
    const int64_t* tts,
    const double* o2_sensor1,
    const double* o2_sensor2,
    const double* o2_sensor3,
    const double* o2_sensor4,
    const double* o2_sensor5,
    const double* o2_sensor6,
    const int64_t* o2_sensor_mv1,
    const int64_t* o2_sensor_mv2,
    const int64_t* o2_sensor_mv3,
    const int64_t* o2_sensor_mv4,
    const int64_t* o2_sensor_mv5,
    const int64_t* o2_sensor_mv6,
    const int64_t* gas_mix_index);

  int64_t time_seconds() const;
  void set_time_seconds(int64_t value_arg);

  double depth_meters() const;
  void set_depth_meters(double value_arg);

  const double* temperature_celsius() const;
  void set_temperature_celsius(const double* value_arg);
  void set_temperature_celsius(double value_arg);

  const double* pressure_bar() const;
  void set_pressure_bar(const double* value_arg);
  void set_pressure_bar(double value_arg);

  const int64_t* tank_index() const;
  void set_tank_index(const int64_t* value_arg);
  void set_tank_index(int64_t value_arg);

  // Every tank's pressure in bar at this sample, indexed by tank index, with
  // null where that tank reported nothing. libdivecomputer fires one pressure
  // reading per air-integrated transmitter, so a single sample can carry
  // several; [pressureBar]/[tankIndex] hold only the last of them and lose the
  // rest (issue #1223). Null when the sample carries no pressure at all, and
  // trimmed of trailing nulls, so an ordinary single-transmitter dive costs one
  // short list per sample.
  const flutter::EncodableList* tank_pressures_bar() const;
  void set_tank_pressures_bar(const flutter::EncodableList* value_arg);
  void set_tank_pressures_bar(const flutter::EncodableList& value_arg);

  const int64_t* heart_rate() const;
  void set_heart_rate(const int64_t* value_arg);
  void set_heart_rate(int64_t value_arg);

  // Compass heading in degrees (0-359) from DC_SAMPLE_BEARING; null when the
  // computer does not report bearing samples.
  const double* heading() const;
  void set_heading(const double* value_arg);
  void set_heading(double value_arg);

  const double* setpoint() const;
  void set_setpoint(const double* value_arg);
  void set_setpoint(double value_arg);

  const double* ppo2() const;
  void set_ppo2(const double* value_arg);
  void set_ppo2(double value_arg);

  const double* cns() const;
  void set_cns(const double* value_arg);
  void set_cns(double value_arg);

  const int64_t* rbt() const;
  void set_rbt(const int64_t* value_arg);
  void set_rbt(int64_t value_arg);

  const int64_t* deco_type() const;
  void set_deco_type(const int64_t* value_arg);
  void set_deco_type(int64_t value_arg);

  const int64_t* deco_time() const;
  void set_deco_time(const int64_t* value_arg);
  void set_deco_time(int64_t value_arg);

  const double* deco_depth() const;
  void set_deco_depth(const double* value_arg);
  void set_deco_depth(double value_arg);

  const int64_t* tts() const;
  void set_tts(const int64_t* value_arg);
  void set_tts(int64_t value_arg);

  // Individual CCR O2 cell ppO2 readings in bar (sensor 1..6), null when that
  // cell has no reading. libdivecomputer reports these per-sensor via
  // DC_SAMPLE_PPO2; [ppo2] holds the aggregate/computed value.
  const double* o2_sensor1() const;
  void set_o2_sensor1(const double* value_arg);
  void set_o2_sensor1(double value_arg);

  const double* o2_sensor2() const;
  void set_o2_sensor2(const double* value_arg);
  void set_o2_sensor2(double value_arg);

  const double* o2_sensor3() const;
  void set_o2_sensor3(const double* value_arg);
  void set_o2_sensor3(double value_arg);

  const double* o2_sensor4() const;
  void set_o2_sensor4(const double* value_arg);
  void set_o2_sensor4(double value_arg);

  const double* o2_sensor5() const;
  void set_o2_sensor5(const double* value_arg);
  void set_o2_sensor5(double value_arg);

  const double* o2_sensor6() const;
  void set_o2_sensor6(const double* value_arg);
  void set_o2_sensor6(double value_arg);

  // Raw O2 cell output in millivolts (sensor 1..6), null when that cell
  // reports none. Present even when the cell's ppO2 is unavailable because the
  // logged calibration could not be trusted (issue #810).
  const int64_t* o2_sensor_mv1() const;
  void set_o2_sensor_mv1(const int64_t* value_arg);
  void set_o2_sensor_mv1(int64_t value_arg);

  const int64_t* o2_sensor_mv2() const;
  void set_o2_sensor_mv2(const int64_t* value_arg);
  void set_o2_sensor_mv2(int64_t value_arg);

  const int64_t* o2_sensor_mv3() const;
  void set_o2_sensor_mv3(const int64_t* value_arg);
  void set_o2_sensor_mv3(int64_t value_arg);

  const int64_t* o2_sensor_mv4() const;
  void set_o2_sensor_mv4(const int64_t* value_arg);
  void set_o2_sensor_mv4(int64_t value_arg);

  const int64_t* o2_sensor_mv5() const;
  void set_o2_sensor_mv5(const int64_t* value_arg);
  void set_o2_sensor_mv5(int64_t value_arg);

  const int64_t* o2_sensor_mv6() const;
  void set_o2_sensor_mv6(const int64_t* value_arg);
  void set_o2_sensor_mv6(int64_t value_arg);

  // Active gas mix index at this sample (from DC_SAMPLE_GASMIX), carried forward
  // from the most recent gas switch; null if the computer reported no gas.
  const int64_t* gas_mix_index() const;
  void set_gas_mix_index(const int64_t* value_arg);
  void set_gas_mix_index(int64_t value_arg);


 private:
  static ProfileSample FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class DiveComputerHostApi;
  friend class DiveComputerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t time_seconds_;
  double depth_meters_;
  std::optional<double> temperature_celsius_;
  std::optional<double> pressure_bar_;
  std::optional<int64_t> tank_index_;
  std::optional<flutter::EncodableList> tank_pressures_bar_;
  std::optional<int64_t> heart_rate_;
  std::optional<double> heading_;
  std::optional<double> setpoint_;
  std::optional<double> ppo2_;
  std::optional<double> cns_;
  std::optional<int64_t> rbt_;
  std::optional<int64_t> deco_type_;
  std::optional<int64_t> deco_time_;
  std::optional<double> deco_depth_;
  std::optional<int64_t> tts_;
  std::optional<double> o2_sensor1_;
  std::optional<double> o2_sensor2_;
  std::optional<double> o2_sensor3_;
  std::optional<double> o2_sensor4_;
  std::optional<double> o2_sensor5_;
  std::optional<double> o2_sensor6_;
  std::optional<int64_t> o2_sensor_mv1_;
  std::optional<int64_t> o2_sensor_mv2_;
  std::optional<int64_t> o2_sensor_mv3_;
  std::optional<int64_t> o2_sensor_mv4_;
  std::optional<int64_t> o2_sensor_mv5_;
  std::optional<int64_t> o2_sensor_mv6_;
  std::optional<int64_t> gas_mix_index_;

};


// Generated class from Pigeon that represents data sent in messages.
class GasMix {
 public:
  // Constructs an object setting all fields.
  explicit GasMix(
    int64_t index,
    double o2_percent,
    double he_percent);

  int64_t index() const;
  void set_index(int64_t value_arg);

  double o2_percent() const;
  void set_o2_percent(double value_arg);

  double he_percent() const;
  void set_he_percent(double value_arg);


 private:
  static GasMix FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class DiveComputerHostApi;
  friend class DiveComputerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t index_;
  double o2_percent_;
  double he_percent_;

};


// Generated class from Pigeon that represents data sent in messages.
class TankInfo {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit TankInfo(
    int64_t index,
    int64_t gas_mix_index);

  // Constructs an object setting all fields.
  explicit TankInfo(
    int64_t index,
    int64_t gas_mix_index,
    const double* volume_liters,
    const double* start_pressure_bar,
    const double* end_pressure_bar,
    const int64_t* usage,
    const int64_t* transmitter_serial);

  int64_t index() const;
  void set_index(int64_t value_arg);

  int64_t gas_mix_index() const;
  void set_gas_mix_index(int64_t value_arg);

  const double* volume_liters() const;
  void set_volume_liters(const double* value_arg);
  void set_volume_liters(double value_arg);

  const double* start_pressure_bar() const;
  void set_start_pressure_bar(const double* value_arg);
  void set_start_pressure_bar(double value_arg);

  const double* end_pressure_bar() const;
  void set_end_pressure_bar(const double* value_arg);
  void set_end_pressure_bar(double value_arg);

  // Tank usage from libdivecomputer's `dc_usage_t` (1=oxygen, 2=diluent,
  // 3=sidemount); null when the computer reported no usage (DC_USAGE_NONE).
  const int64_t* usage() const;
  void set_usage(const int64_t* value_arg);
  void set_usage(int64_t value_arg);

  // Serial number of the air-integration transmitter that reported this
  // tank's pressures (`dc_tank_t.serial`, a fork extension); null when the
  // computer reported none. Identifies the physical cylinder across
  // computers paired to the same transmitter.
  const int64_t* transmitter_serial() const;
  void set_transmitter_serial(const int64_t* value_arg);
  void set_transmitter_serial(int64_t value_arg);


 private:
  static TankInfo FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class DiveComputerHostApi;
  friend class DiveComputerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t index_;
  int64_t gas_mix_index_;
  std::optional<double> volume_liters_;
  std::optional<double> start_pressure_bar_;
  std::optional<double> end_pressure_bar_;
  std::optional<int64_t> usage_;
  std::optional<int64_t> transmitter_serial_;

};


// Generated class from Pigeon that represents data sent in messages.
class DiveEvent {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit DiveEvent(
    int64_t time_seconds,
    const std::string& type);

  // Constructs an object setting all fields.
  explicit DiveEvent(
    int64_t time_seconds,
    const std::string& type,
    const flutter::EncodableMap* data);

  int64_t time_seconds() const;
  void set_time_seconds(int64_t value_arg);

  const std::string& type() const;
  void set_type(std::string_view value_arg);

  const flutter::EncodableMap* data() const;
  void set_data(const flutter::EncodableMap* value_arg);
  void set_data(const flutter::EncodableMap& value_arg);


 private:
  static DiveEvent FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class DiveComputerHostApi;
  friend class DiveComputerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t time_seconds_;
  std::string type_;
  std::optional<flutter::EncodableMap> data_;

};


// Generated class from Pigeon that represents data sent in messages.
class ParsedDive {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit ParsedDive(
    const std::string& fingerprint,
    int64_t date_time_year,
    int64_t date_time_month,
    int64_t date_time_day,
    int64_t date_time_hour,
    int64_t date_time_minute,
    int64_t date_time_second,
    double max_depth_meters,
    double avg_depth_meters,
    int64_t duration_seconds,
    const flutter::EncodableList& samples,
    const flutter::EncodableList& tanks,
    const flutter::EncodableList& gas_mixes,
    const flutter::EncodableList& events);

  // Constructs an object setting all fields.
  explicit ParsedDive(
    const std::string& fingerprint,
    int64_t date_time_year,
    int64_t date_time_month,
    int64_t date_time_day,
    int64_t date_time_hour,
    int64_t date_time_minute,
    int64_t date_time_second,
    const int64_t* date_time_timezone_offset,
    double max_depth_meters,
    double avg_depth_meters,
    int64_t duration_seconds,
    const double* min_temperature_celsius,
    const double* max_temperature_celsius,
    const flutter::EncodableList& samples,
    const flutter::EncodableList& tanks,
    const flutter::EncodableList& gas_mixes,
    const flutter::EncodableList& events,
    const std::string* dive_mode,
    const std::string* deco_algorithm,
    const int64_t* gf_low,
    const int64_t* gf_high,
    const int64_t* deco_conservatism,
    const std::vector<uint8_t>* raw_data,
    const std::vector<uint8_t>* raw_fingerprint,
    const double* entry_latitude,
    const double* entry_longitude,
    const double* exit_latitude,
    const double* exit_longitude,
    const double* ppo2_max_bar);

  const std::string& fingerprint() const;
  void set_fingerprint(std::string_view value_arg);

  int64_t date_time_year() const;
  void set_date_time_year(int64_t value_arg);

  int64_t date_time_month() const;
  void set_date_time_month(int64_t value_arg);

  int64_t date_time_day() const;
  void set_date_time_day(int64_t value_arg);

  int64_t date_time_hour() const;
  void set_date_time_hour(int64_t value_arg);

  int64_t date_time_minute() const;
  void set_date_time_minute(int64_t value_arg);

  int64_t date_time_second() const;
  void set_date_time_second(int64_t value_arg);

  const int64_t* date_time_timezone_offset() const;
  void set_date_time_timezone_offset(const int64_t* value_arg);
  void set_date_time_timezone_offset(int64_t value_arg);

  double max_depth_meters() const;
  void set_max_depth_meters(double value_arg);

  double avg_depth_meters() const;
  void set_avg_depth_meters(double value_arg);

  int64_t duration_seconds() const;
  void set_duration_seconds(int64_t value_arg);

  const double* min_temperature_celsius() const;
  void set_min_temperature_celsius(const double* value_arg);
  void set_min_temperature_celsius(double value_arg);

  const double* max_temperature_celsius() const;
  void set_max_temperature_celsius(const double* value_arg);
  void set_max_temperature_celsius(double value_arg);

  const flutter::EncodableList& samples() const;
  void set_samples(const flutter::EncodableList& value_arg);

  const flutter::EncodableList& tanks() const;
  void set_tanks(const flutter::EncodableList& value_arg);

  const flutter::EncodableList& gas_mixes() const;
  void set_gas_mixes(const flutter::EncodableList& value_arg);

  const flutter::EncodableList& events() const;
  void set_events(const flutter::EncodableList& value_arg);

  const std::string* dive_mode() const;
  void set_dive_mode(const std::string_view* value_arg);
  void set_dive_mode(std::string_view value_arg);

  const std::string* deco_algorithm() const;
  void set_deco_algorithm(const std::string_view* value_arg);
  void set_deco_algorithm(std::string_view value_arg);

  const int64_t* gf_low() const;
  void set_gf_low(const int64_t* value_arg);
  void set_gf_low(int64_t value_arg);

  const int64_t* gf_high() const;
  void set_gf_high(const int64_t* value_arg);
  void set_gf_high(int64_t value_arg);

  const int64_t* deco_conservatism() const;
  void set_deco_conservatism(const int64_t* value_arg);
  void set_deco_conservatism(int64_t value_arg);

  const std::vector<uint8_t>* raw_data() const;
  void set_raw_data(const std::vector<uint8_t>* value_arg);
  void set_raw_data(const std::vector<uint8_t>& value_arg);

  const std::vector<uint8_t>* raw_fingerprint() const;
  void set_raw_fingerprint(const std::vector<uint8_t>* value_arg);
  void set_raw_fingerprint(const std::vector<uint8_t>& value_arg);

  const double* entry_latitude() const;
  void set_entry_latitude(const double* value_arg);
  void set_entry_latitude(double value_arg);

  const double* entry_longitude() const;
  void set_entry_longitude(const double* value_arg);
  void set_entry_longitude(double value_arg);

  const double* exit_latitude() const;
  void set_exit_latitude(const double* value_arg);
  void set_exit_latitude(double value_arg);

  const double* exit_longitude() const;
  void set_exit_longitude(const double* value_arg);
  void set_exit_longitude(double value_arg);

  const double* ppo2_max_bar() const;
  void set_ppo2_max_bar(const double* value_arg);
  void set_ppo2_max_bar(double value_arg);


 private:
  static ParsedDive FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class DiveComputerHostApi;
  friend class DiveComputerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string fingerprint_;
  int64_t date_time_year_;
  int64_t date_time_month_;
  int64_t date_time_day_;
  int64_t date_time_hour_;
  int64_t date_time_minute_;
  int64_t date_time_second_;
  std::optional<int64_t> date_time_timezone_offset_;
  double max_depth_meters_;
  double avg_depth_meters_;
  int64_t duration_seconds_;
  std::optional<double> min_temperature_celsius_;
  std::optional<double> max_temperature_celsius_;
  flutter::EncodableList samples_;
  flutter::EncodableList tanks_;
  flutter::EncodableList gas_mixes_;
  flutter::EncodableList events_;
  std::optional<std::string> dive_mode_;
  std::optional<std::string> deco_algorithm_;
  std::optional<int64_t> gf_low_;
  std::optional<int64_t> gf_high_;
  std::optional<int64_t> deco_conservatism_;
  std::optional<std::vector<uint8_t>> raw_data_;
  std::optional<std::vector<uint8_t>> raw_fingerprint_;
  std::optional<double> entry_latitude_;
  std::optional<double> entry_longitude_;
  std::optional<double> exit_latitude_;
  std::optional<double> exit_longitude_;
  std::optional<double> ppo2_max_bar_;

};


// Generated class from Pigeon that represents data sent in messages.
class DownloadProgress {
 public:
  // Constructs an object setting all fields.
  explicit DownloadProgress(
    int64_t current,
    int64_t total,
    const std::string& status);

  int64_t current() const;
  void set_current(int64_t value_arg);

  int64_t total() const;
  void set_total(int64_t value_arg);

  const std::string& status() const;
  void set_status(std::string_view value_arg);


 private:
  static DownloadProgress FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class DiveComputerHostApi;
  friend class DiveComputerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  int64_t current_;
  int64_t total_;
  std::string status_;

};


// Generated class from Pigeon that represents data sent in messages.
class DiveComputerError {
 public:
  // Constructs an object setting all fields.
  explicit DiveComputerError(
    const std::string& code,
    const std::string& message);

  const std::string& code() const;
  void set_code(std::string_view value_arg);

  const std::string& message() const;
  void set_message(std::string_view value_arg);


 private:
  static DiveComputerError FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class DiveComputerHostApi;
  friend class DiveComputerFlutterApi;
  friend class PigeonInternalCodecSerializer;
  std::string code_;
  std::string message_;

};


class PigeonInternalCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  PigeonInternalCodecSerializer();
  inline static PigeonInternalCodecSerializer& GetInstance() {
    static PigeonInternalCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class DiveComputerHostApi {
 public:
  DiveComputerHostApi(const DiveComputerHostApi&) = delete;
  DiveComputerHostApi& operator=(const DiveComputerHostApi&) = delete;
  virtual ~DiveComputerHostApi() {}
  virtual void GetDeviceDescriptors(std::function<void(ErrorOr<flutter::EncodableList> reply)> result) = 0;
  virtual void StartDiscovery(
    const TransportType& transport,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual std::optional<FlutterError> StopDiscovery() = 0;
  virtual void StartDownload(
    const DiscoveredDevice& device,
    const std::string* fingerprint,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual std::optional<FlutterError> CancelDownload() = 0;
  virtual std::optional<FlutterError> SubmitPinCode(const std::string& pin_code) = 0;
  virtual ErrorOr<std::string> GetLibdivecomputerVersion() = 0;
  virtual void ParseRawDiveData(
    const std::string& vendor,
    const std::string& product,
    int64_t model,
    const std::vector<uint8_t>& data,
    std::function<void(ErrorOr<ParsedDive> reply)> result) = 0;

  // The codec used by DiveComputerHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `DiveComputerHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    DiveComputerHostApi* api);
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    DiveComputerHostApi* api,
    const std::string& message_channel_suffix);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  DiveComputerHostApi() = default;

};
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class DiveComputerFlutterApi {
 public:
  DiveComputerFlutterApi(flutter::BinaryMessenger* binary_messenger);
  DiveComputerFlutterApi(
    flutter::BinaryMessenger* binary_messenger,
    const std::string& message_channel_suffix);
  static const flutter::StandardMessageCodec& GetCodec();
  void OnDeviceDiscovered(
    const DiscoveredDevice& device,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnDiscoveryComplete(
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnDownloadProgress(
    const DownloadProgress& progress,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnDiveDownloaded(
    const ParsedDive& dive,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnDownloadComplete(
    int64_t total_dives,
    const std::string* serial_number,
    const std::string* firmware_version,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnError(
    const DiveComputerError& error,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnPinCodeRequired(
    const std::string& device_address,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);
  void OnLogEvent(
    const std::string& category,
    const std::string& level,
    const std::string& message,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);

 private:
  flutter::BinaryMessenger* binary_messenger_;
  std::string message_channel_suffix_;
};

}  // namespace libdivecomputer_plugin
#endif  // PIGEON_DIVE_COMPUTER_API_G_H_
