// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum TransportType: Int {
  case ble = 0
  case usb = 1
  case serial = 2
  case infrared = 3
}

/// Generated class from Pigeon that represents data sent in messages.
struct DeviceDescriptor {
  var vendor: String
  var product: String
  var model: Int64
  var transports: [TransportType]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeviceDescriptor? {
    let vendor = pigeonVar_list[0] as! String
    let product = pigeonVar_list[1] as! String
    let model = pigeonVar_list[2] as! Int64
    let transports = pigeonVar_list[3] as! [TransportType]

    return DeviceDescriptor(
      vendor: vendor,
      product: product,
      model: model,
      transports: transports
    )
  }
  func toList() -> [Any?] {
    return [
      vendor,
      product,
      model,
      transports,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DiscoveredDevice {
  var vendor: String
  var product: String
  var model: Int64
  var address: String
  var name: String? = nil
  var transport: TransportType


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DiscoveredDevice? {
    let vendor = pigeonVar_list[0] as! String
    let product = pigeonVar_list[1] as! String
    let model = pigeonVar_list[2] as! Int64
    let address = pigeonVar_list[3] as! String
    let name: String? = nilOrValue(pigeonVar_list[4])
    let transport = pigeonVar_list[5] as! TransportType

    return DiscoveredDevice(
      vendor: vendor,
      product: product,
      model: model,
      address: address,
      name: name,
      transport: transport
    )
  }
  func toList() -> [Any?] {
    return [
      vendor,
      product,
      model,
      address,
      name,
      transport,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProfileSample {
  var timeSeconds: Int64
  var depthMeters: Double
  var temperatureCelsius: Double? = nil
  var pressureBar: Double? = nil
  var tankIndex: Int64? = nil
  /// Every tank's pressure in bar at this sample, indexed by tank index, with
  /// null where that tank reported nothing. libdivecomputer fires one pressure
  /// reading per air-integrated transmitter, so a single sample can carry
  /// several; [pressureBar]/[tankIndex] hold only the last of them and lose the
  /// rest (issue #1223). Null when the sample carries no pressure at all, and
  /// trimmed of trailing nulls, so an ordinary single-transmitter dive costs one
  /// short list per sample.
  var tankPressuresBar: [Double?]? = nil
  var heartRate: Int64? = nil
  /// Compass heading in degrees (0-359) from DC_SAMPLE_BEARING; null when the
  /// computer does not report bearing samples.
  var heading: Double? = nil
  var setpoint: Double? = nil
  var ppo2: Double? = nil
  var cns: Double? = nil
  var rbt: Int64? = nil
  var decoType: Int64? = nil
  var decoTime: Int64? = nil
  var decoDepth: Double? = nil
  var tts: Int64? = nil
  /// Individual CCR O2 cell ppO2 readings in bar (sensor 1..6), null when that
  /// cell has no reading. libdivecomputer reports these per-sensor via
  /// DC_SAMPLE_PPO2; [ppo2] holds the aggregate/computed value.
  var o2Sensor1: Double? = nil
  var o2Sensor2: Double? = nil
  var o2Sensor3: Double? = nil
  var o2Sensor4: Double? = nil
  var o2Sensor5: Double? = nil
  var o2Sensor6: Double? = nil
  /// Raw O2 cell output in millivolts (sensor 1..6), null when that cell
  /// reports none. Present even when the cell's ppO2 is unavailable because the
  /// logged calibration could not be trusted (issue #810).
  var o2SensorMv1: Int64? = nil
  var o2SensorMv2: Int64? = nil
  var o2SensorMv3: Int64? = nil
  var o2SensorMv4: Int64? = nil
  var o2SensorMv5: Int64? = nil
  var o2SensorMv6: Int64? = nil
  /// Active gas mix index at this sample (from DC_SAMPLE_GASMIX), carried forward
  /// from the most recent gas switch; null if the computer reported no gas.
  var gasMixIndex: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProfileSample? {
    let timeSeconds = pigeonVar_list[0] as! Int64
    let depthMeters = pigeonVar_list[1] as! Double
    let temperatureCelsius: Double? = nilOrValue(pigeonVar_list[2])
    let pressureBar: Double? = nilOrValue(pigeonVar_list[3])
    let tankIndex: Int64? = nilOrValue(pigeonVar_list[4])
    let tankPressuresBar: [Double?]? = nilOrValue(pigeonVar_list[5])
    let heartRate: Int64? = nilOrValue(pigeonVar_list[6])
    let heading: Double? = nilOrValue(pigeonVar_list[7])
    let setpoint: Double? = nilOrValue(pigeonVar_list[8])
    let ppo2: Double? = nilOrValue(pigeonVar_list[9])
    let cns: Double? = nilOrValue(pigeonVar_list[10])
    let rbt: Int64? = nilOrValue(pigeonVar_list[11])
    let decoType: Int64? = nilOrValue(pigeonVar_list[12])
    let decoTime: Int64? = nilOrValue(pigeonVar_list[13])
    let decoDepth: Double? = nilOrValue(pigeonVar_list[14])
    let tts: Int64? = nilOrValue(pigeonVar_list[15])
    let o2Sensor1: Double? = nilOrValue(pigeonVar_list[16])
    let o2Sensor2: Double? = nilOrValue(pigeonVar_list[17])
    let o2Sensor3: Double? = nilOrValue(pigeonVar_list[18])
    let o2Sensor4: Double? = nilOrValue(pigeonVar_list[19])
    let o2Sensor5: Double? = nilOrValue(pigeonVar_list[20])
    let o2Sensor6: Double? = nilOrValue(pigeonVar_list[21])
    let o2SensorMv1: Int64? = nilOrValue(pigeonVar_list[22])
    let o2SensorMv2: Int64? = nilOrValue(pigeonVar_list[23])
    let o2SensorMv3: Int64? = nilOrValue(pigeonVar_list[24])
    let o2SensorMv4: Int64? = nilOrValue(pigeonVar_list[25])
    let o2SensorMv5: Int64? = nilOrValue(pigeonVar_list[26])
    let o2SensorMv6: Int64? = nilOrValue(pigeonVar_list[27])
    let gasMixIndex: Int64? = nilOrValue(pigeonVar_list[28])

    return ProfileSample(
      timeSeconds: timeSeconds,
      depthMeters: depthMeters,
      temperatureCelsius: temperatureCelsius,
      pressureBar: pressureBar,
      tankIndex: tankIndex,
      tankPressuresBar: tankPressuresBar,
      heartRate: heartRate,
      heading: heading,
      setpoint: setpoint,
      ppo2: ppo2,
      cns: cns,
      rbt: rbt,
      decoType: decoType,
      decoTime: decoTime,
      decoDepth: decoDepth,
      tts: tts,
      o2Sensor1: o2Sensor1,
      o2Sensor2: o2Sensor2,
      o2Sensor3: o2Sensor3,
      o2Sensor4: o2Sensor4,
      o2Sensor5: o2Sensor5,
      o2Sensor6: o2Sensor6,
      o2SensorMv1: o2SensorMv1,
      o2SensorMv2: o2SensorMv2,
      o2SensorMv3: o2SensorMv3,
      o2SensorMv4: o2SensorMv4,
      o2SensorMv5: o2SensorMv5,
      o2SensorMv6: o2SensorMv6,
      gasMixIndex: gasMixIndex
    )
  }
  func toList() -> [Any?] {
    return [
      timeSeconds,
      depthMeters,
      temperatureCelsius,
      pressureBar,
      tankIndex,
      tankPressuresBar,
      heartRate,
      heading,
      setpoint,
      ppo2,
      cns,
      rbt,
      decoType,
      decoTime,
      decoDepth,
      tts,
      o2Sensor1,
      o2Sensor2,
      o2Sensor3,
      o2Sensor4,
      o2Sensor5,
      o2Sensor6,
      o2SensorMv1,
      o2SensorMv2,
      o2SensorMv3,
      o2SensorMv4,
      o2SensorMv5,
      o2SensorMv6,
      gasMixIndex,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GasMix {
  var index: Int64
  var o2Percent: Double
  var hePercent: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GasMix? {
    let index = pigeonVar_list[0] as! Int64
    let o2Percent = pigeonVar_list[1] as! Double
    let hePercent = pigeonVar_list[2] as! Double

    return GasMix(
      index: index,
      o2Percent: o2Percent,
      hePercent: hePercent
    )
  }
  func toList() -> [Any?] {
    return [
      index,
      o2Percent,
      hePercent,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TankInfo {
  var index: Int64
  var gasMixIndex: Int64
  var volumeLiters: Double? = nil
  var startPressureBar: Double? = nil
  var endPressureBar: Double? = nil
  /// Tank usage from libdivecomputer's `dc_usage_t` (1=oxygen, 2=diluent,
  /// 3=sidemount); null when the computer reported no usage (DC_USAGE_NONE).
  var usage: Int64? = nil
  /// Serial number of the air-integration transmitter that reported this
  /// tank's pressures (`dc_tank_t.serial`, a fork extension); null when the
  /// computer reported none. Identifies the physical cylinder across
  /// computers paired to the same transmitter.
  var transmitterSerial: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TankInfo? {
    let index = pigeonVar_list[0] as! Int64
    let gasMixIndex = pigeonVar_list[1] as! Int64
    let volumeLiters: Double? = nilOrValue(pigeonVar_list[2])
    let startPressureBar: Double? = nilOrValue(pigeonVar_list[3])
    let endPressureBar: Double? = nilOrValue(pigeonVar_list[4])
    let usage: Int64? = nilOrValue(pigeonVar_list[5])
    let transmitterSerial: Int64? = nilOrValue(pigeonVar_list[6])

    return TankInfo(
      index: index,
      gasMixIndex: gasMixIndex,
      volumeLiters: volumeLiters,
      startPressureBar: startPressureBar,
      endPressureBar: endPressureBar,
      usage: usage,
      transmitterSerial: transmitterSerial
    )
  }
  func toList() -> [Any?] {
    return [
      index,
      gasMixIndex,
      volumeLiters,
      startPressureBar,
      endPressureBar,
      usage,
      transmitterSerial,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DiveEvent {
  var timeSeconds: Int64
  var type: String
  var data: [String: String]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DiveEvent? {
    let timeSeconds = pigeonVar_list[0] as! Int64
    let type = pigeonVar_list[1] as! String
    let data: [String: String]? = nilOrValue(pigeonVar_list[2])

    return DiveEvent(
      timeSeconds: timeSeconds,
      type: type,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      timeSeconds,
      type,
      data,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ParsedDive {
  var fingerprint: String
  var dateTimeYear: Int64
  var dateTimeMonth: Int64
  var dateTimeDay: Int64
  var dateTimeHour: Int64
  var dateTimeMinute: Int64
  var dateTimeSecond: Int64
  var dateTimeTimezoneOffset: Int64? = nil
  var maxDepthMeters: Double
  var avgDepthMeters: Double
  var durationSeconds: Int64
  var minTemperatureCelsius: Double? = nil
  var maxTemperatureCelsius: Double? = nil
  var samples: [ProfileSample]
  var tanks: [TankInfo]
  var gasMixes: [GasMix]
  var events: [DiveEvent]
  var diveMode: String? = nil
  var decoAlgorithm: String? = nil
  var gfLow: Int64? = nil
  var gfHigh: Int64? = nil
  var decoConservatism: Int64? = nil
  var rawData: FlutterStandardTypedData? = nil
  var rawFingerprint: FlutterStandardTypedData? = nil
  var entryLatitude: Double? = nil
  var entryLongitude: Double? = nil
  var exitLatitude: Double? = nil
  var exitLongitude: Double? = nil
  var ppO2MaxBar: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ParsedDive? {
    let fingerprint = pigeonVar_list[0] as! String
    let dateTimeYear = pigeonVar_list[1] as! Int64
    let dateTimeMonth = pigeonVar_list[2] as! Int64
    let dateTimeDay = pigeonVar_list[3] as! Int64
    let dateTimeHour = pigeonVar_list[4] as! Int64
    let dateTimeMinute = pigeonVar_list[5] as! Int64
    let dateTimeSecond = pigeonVar_list[6] as! Int64
    let dateTimeTimezoneOffset: Int64? = nilOrValue(pigeonVar_list[7])
    let maxDepthMeters = pigeonVar_list[8] as! Double
    let avgDepthMeters = pigeonVar_list[9] as! Double
    let durationSeconds = pigeonVar_list[10] as! Int64
    let minTemperatureCelsius: Double? = nilOrValue(pigeonVar_list[11])
    let maxTemperatureCelsius: Double? = nilOrValue(pigeonVar_list[12])
    let samples = pigeonVar_list[13] as! [ProfileSample]
    let tanks = pigeonVar_list[14] as! [TankInfo]
    let gasMixes = pigeonVar_list[15] as! [GasMix]
    let events = pigeonVar_list[16] as! [DiveEvent]
    let diveMode: String? = nilOrValue(pigeonVar_list[17])
    let decoAlgorithm: String? = nilOrValue(pigeonVar_list[18])
    let gfLow: Int64? = nilOrValue(pigeonVar_list[19])
    let gfHigh: Int64? = nilOrValue(pigeonVar_list[20])
    let decoConservatism: Int64? = nilOrValue(pigeonVar_list[21])
    let rawData: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[22])
    let rawFingerprint: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[23])
    let entryLatitude: Double? = nilOrValue(pigeonVar_list[24])
    let entryLongitude: Double? = nilOrValue(pigeonVar_list[25])
    let exitLatitude: Double? = nilOrValue(pigeonVar_list[26])
    let exitLongitude: Double? = nilOrValue(pigeonVar_list[27])
    let ppO2MaxBar: Double? = nilOrValue(pigeonVar_list[28])

    return ParsedDive(
      fingerprint: fingerprint,
      dateTimeYear: dateTimeYear,
      dateTimeMonth: dateTimeMonth,
      dateTimeDay: dateTimeDay,
      dateTimeHour: dateTimeHour,
      dateTimeMinute: dateTimeMinute,
      dateTimeSecond: dateTimeSecond,
      dateTimeTimezoneOffset: dateTimeTimezoneOffset,
      maxDepthMeters: maxDepthMeters,
      avgDepthMeters: avgDepthMeters,
      durationSeconds: durationSeconds,
      minTemperatureCelsius: minTemperatureCelsius,
      maxTemperatureCelsius: maxTemperatureCelsius,
      samples: samples,
      tanks: tanks,
      gasMixes: gasMixes,
      events: events,
      diveMode: diveMode,
      decoAlgorithm: decoAlgorithm,
      gfLow: gfLow,
      gfHigh: gfHigh,
      decoConservatism: decoConservatism,
      rawData: rawData,
      rawFingerprint: rawFingerprint,
      entryLatitude: entryLatitude,
      entryLongitude: entryLongitude,
      exitLatitude: exitLatitude,
      exitLongitude: exitLongitude,
      ppO2MaxBar: ppO2MaxBar
    )
  }
  func toList() -> [Any?] {
    return [
      fingerprint,
      dateTimeYear,
      dateTimeMonth,
      dateTimeDay,
      dateTimeHour,
      dateTimeMinute,
      dateTimeSecond,
      dateTimeTimezoneOffset,
      maxDepthMeters,
      avgDepthMeters,
      durationSeconds,
      minTemperatureCelsius,
      maxTemperatureCelsius,
      samples,
      tanks,
      gasMixes,
      events,
      diveMode,
      decoAlgorithm,
      gfLow,
      gfHigh,
      decoConservatism,
      rawData,
      rawFingerprint,
      entryLatitude,
      entryLongitude,
      exitLatitude,
      exitLongitude,
      ppO2MaxBar,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DownloadProgress {
  var current: Int64
  var total: Int64
  var status: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DownloadProgress? {
    let current = pigeonVar_list[0] as! Int64
    let total = pigeonVar_list[1] as! Int64
    let status = pigeonVar_list[2] as! String

    return DownloadProgress(
      current: current,
      total: total,
      status: status
    )
  }
  func toList() -> [Any?] {
    return [
      current,
      total,
      status,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DiveComputerError {
  var code: String
  var message: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DiveComputerError? {
    let code = pigeonVar_list[0] as! String
    let message = pigeonVar_list[1] as! String

    return DiveComputerError(
      code: code,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      message,
    ]
  }
}

private class DiveComputerApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TransportType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return DeviceDescriptor.fromList(self.readValue() as! [Any?])
    case 131:
      return DiscoveredDevice.fromList(self.readValue() as! [Any?])
    case 132:
      return ProfileSample.fromList(self.readValue() as! [Any?])
    case 133:
      return GasMix.fromList(self.readValue() as! [Any?])
    case 134:
      return TankInfo.fromList(self.readValue() as! [Any?])
    case 135:
      return DiveEvent.fromList(self.readValue() as! [Any?])
    case 136:
      return ParsedDive.fromList(self.readValue() as! [Any?])
    case 137:
      return DownloadProgress.fromList(self.readValue() as! [Any?])
    case 138:
      return DiveComputerError.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class DiveComputerApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? TransportType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? DeviceDescriptor {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? DiscoveredDevice {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? ProfileSample {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? GasMix {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? TankInfo {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? DiveEvent {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? ParsedDive {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? DownloadProgress {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? DiveComputerError {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class DiveComputerApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return DiveComputerApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return DiveComputerApiPigeonCodecWriter(data: data)
  }
}

class DiveComputerApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = DiveComputerApiPigeonCodec(readerWriter: DiveComputerApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DiveComputerHostApi {
  func getDeviceDescriptors(completion: @escaping (Result<[DeviceDescriptor], Error>) -> Void)
  func startDiscovery(transport: TransportType, completion: @escaping (Result<Void, Error>) -> Void)
  func stopDiscovery() throws
  func startDownload(device: DiscoveredDevice, fingerprint: String?, completion: @escaping (Result<Void, Error>) -> Void)
  func cancelDownload() throws
  func submitPinCode(pinCode: String) throws
  func getLibdivecomputerVersion() throws -> String
  func parseRawDiveData(vendor: String, product: String, model: Int64, data: FlutterStandardTypedData, completion: @escaping (Result<ParsedDive, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DiveComputerHostApiSetup {
  static var codec: FlutterStandardMessageCodec { DiveComputerApiPigeonCodec.shared }
  /// Sets up an instance of `DiveComputerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DiveComputerHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getDeviceDescriptorsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.getDeviceDescriptors\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getDeviceDescriptorsChannel.setMessageHandler { _, reply in
        api.getDeviceDescriptors { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getDeviceDescriptorsChannel.setMessageHandler(nil)
    }
    let startDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.startDiscovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDiscoveryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let transportArg = args[0] as! TransportType
        api.startDiscovery(transport: transportArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startDiscoveryChannel.setMessageHandler(nil)
    }
    let stopDiscoveryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.stopDiscovery\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopDiscoveryChannel.setMessageHandler { _, reply in
        do {
          try api.stopDiscovery()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopDiscoveryChannel.setMessageHandler(nil)
    }
    let startDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.startDownload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startDownloadChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceArg = args[0] as! DiscoveredDevice
        let fingerprintArg: String? = nilOrValue(args[1])
        api.startDownload(device: deviceArg, fingerprint: fingerprintArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startDownloadChannel.setMessageHandler(nil)
    }
    let cancelDownloadChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.cancelDownload\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelDownloadChannel.setMessageHandler { _, reply in
        do {
          try api.cancelDownload()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelDownloadChannel.setMessageHandler(nil)
    }
    let submitPinCodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.submitPinCode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      submitPinCodeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pinCodeArg = args[0] as! String
        do {
          try api.submitPinCode(pinCode: pinCodeArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      submitPinCodeChannel.setMessageHandler(nil)
    }
    let getLibdivecomputerVersionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.getLibdivecomputerVersion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLibdivecomputerVersionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getLibdivecomputerVersion()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getLibdivecomputerVersionChannel.setMessageHandler(nil)
    }
    let parseRawDiveDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerHostApi.parseRawDiveData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      parseRawDiveDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let vendorArg = args[0] as! String
        let productArg = args[1] as! String
        let modelArg = args[2] as! Int64
        let dataArg = args[3] as! FlutterStandardTypedData
        api.parseRawDiveData(vendor: vendorArg, product: productArg, model: modelArg, data: dataArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      parseRawDiveDataChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol DiveComputerFlutterApiProtocol {
  func onDeviceDiscovered(device deviceArg: DiscoveredDevice, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDiscoveryComplete(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDownloadProgress(progress progressArg: DownloadProgress, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDiveDownloaded(dive diveArg: ParsedDive, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onDownloadComplete(totalDives totalDivesArg: Int64, serialNumber serialNumberArg: String?, firmwareVersion firmwareVersionArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onError(error errorArg: DiveComputerError, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPinCodeRequired(deviceAddress deviceAddressArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onLogEvent(category categoryArg: String, level levelArg: String, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class DiveComputerFlutterApi: DiveComputerFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: DiveComputerApiPigeonCodec {
    return DiveComputerApiPigeonCodec.shared
  }
  func onDeviceDiscovered(device deviceArg: DiscoveredDevice, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onDeviceDiscovered\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onDiscoveryComplete(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onDiscoveryComplete\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onDownloadProgress(progress progressArg: DownloadProgress, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onDownloadProgress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([progressArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onDiveDownloaded(dive diveArg: ParsedDive, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onDiveDownloaded\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([diveArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onDownloadComplete(totalDives totalDivesArg: Int64, serialNumber serialNumberArg: String?, firmwareVersion firmwareVersionArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onDownloadComplete\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([totalDivesArg, serialNumberArg, firmwareVersionArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onError(error errorArg: DiveComputerError, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onPinCodeRequired(deviceAddress deviceAddressArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onPinCodeRequired\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceAddressArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onLogEvent(category categoryArg: String, level levelArg: String, message messageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.libdivecomputer_plugin.DiveComputerFlutterApi.onLogEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([categoryArg, levelArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
