#!/usr/bin/env python3
"""Generate udev rules for the dive computers libdivecomputer supports.

Upstream ships contrib/udev/libdivecomputer.rules, but it covers only a handful
of devices and every rule reads GROUP="plugdev", a group Fedora does not create.
This generator reads the VID/PID tables out of descriptor.c instead, so a
submodule bump widens hardware support without anyone editing a list, and emits
TAG+="uaccess" so systemd-logind grants access to the user on the active seat.
uaccess needs no group membership, no usermod, and no log out and back in, and
it behaves identically on Debian and Fedora.

Usage:
    gen_udev_rules.py <path/to/descriptor.c>   > 60-submersion-divecomputers.rules
"""

import collections
import re
import sys

Device = collections.namedtuple("Device", "vid pid comment hid")

# The two table shapes in descriptor.c. dc_usbhid_desc_t devices are opened
# through /dev/hidraw*; dc_usb_desc_t devices through the raw USB node.
_TABLE_RE = re.compile(
    r"static\s+const\s+(dc_usbhid_desc_t|dc_usb_desc_t)\s+\w+\s*\[\]\s*=\s*\{(.*?)\};",
    re.DOTALL,
)
_ENTRY_RE = re.compile(
    r"\{\s*0x([0-9a-fA-F]{4})\s*,\s*0x([0-9a-fA-F]{4})\s*\}\s*,?\s*(?://\s*(.*))?"
)

# USB-to-serial bridges used by the serial dive computers. These are not in
# descriptor.c because libdivecomputer addresses them by tty path, not by ID.
# Vendor-wide by necessity: the bridge chip carries the vendor's ID, and the
# dive computer behind it is invisible to udev.
SERIAL_BRIDGES = (
    ("0403", "FTDI (Oceanic, Aeris, Sherwood, Hollis)"),
    ("067b", "Prolific PL2303 (Mares, Cressi)"),
    ("10c4", "Silicon Labs CP210x (Suunto, Uwatec)"),
)

HEADER = """# Submersion dive computer access rules.
#
# Generated by scripts/gen_udev_rules.py from libdivecomputer's descriptor.c.
# Do not edit by hand; edit the generator or bump the submodule.
#
# TAG+="uaccess" hands access to the user on the active seat via
# systemd-logind. No group membership is required, and access follows the
# seat, so it is revoked on fast user switching.
"""


def parse_devices(source):
    """Extract every VID/PID pair from descriptor.c's device tables."""
    devices = []
    for kind, body in _TABLE_RE.findall(source):
        hid = kind == "dc_usbhid_desc_t"
        for vid, pid, comment in _ENTRY_RE.findall(body):
            devices.append(
                Device(vid.lower(), pid.lower(), (comment or "").strip(), hid)
            )
    if not devices:
        sys.exit(
            "gen_udev_rules: no device tables found. descriptor.c's shape "
            "changed; update _TABLE_RE and _ENTRY_RE rather than shipping an "
            "empty rules file."
        )
    return devices


def render(devices):
    """Render the rules file for the given devices."""
    lines = [HEADER]
    for device in devices:
        if device.comment:
            lines.append("# %s" % device.comment)
        if device.hid:
            lines.append(
                'SUBSYSTEM=="hidraw", ATTRS{idVendor}=="%s", '
                'ATTRS{idProduct}=="%s", TAG+="uaccess"' % (device.vid, device.pid)
            )
        lines.append(
            'SUBSYSTEM=="usb", ATTR{idVendor}=="%s", '
            'ATTR{idProduct}=="%s", TAG+="uaccess"' % (device.vid, device.pid)
        )
        lines.append("")

    lines.append("# USB-to-serial bridges (/dev/ttyUSB*)")
    for vid, comment in SERIAL_BRIDGES:
        lines.append("# %s" % comment)
        lines.append('SUBSYSTEM=="tty", ATTRS{idVendor}=="%s", TAG+="uaccess"' % vid)
    lines.append("")
    return "\n".join(lines)


def main(argv):
    if len(argv) != 2:
        sys.exit("usage: gen_udev_rules.py <path/to/descriptor.c>")
    with open(argv[1], "r", encoding="utf-8") as handle:
        source = handle.read()
    sys.stdout.write(render(parse_devices(source)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
