import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:submersion/core/constants/enums.dart';
import 'package:submersion/core/icons/mdi_icons.dart';
import 'package:submersion/core/icons/submersion_icons.dart';
import 'package:submersion/features/equipment/presentation/utils/equipment_type_icon.dart';

/// Proves every glyph the app asks a *vendored* font for actually exists in
/// the committed `.ttf`.
///
/// Nothing else does. Asserting an [IconData]'s `fontFamily` only checks a
/// string, and a code point the font never mapped renders as an empty box on
/// a device while every test stays green. Two real ways that happens here:
///
/// - [MdiIcons] code points are transcribed by hand from the Material Design
///   Icons release notes. A digit typed wrong compiles, analyzes and passes
///   every other test.
/// - The [SubmersionIcons] font is generated by `tool/build_equipment_icon_font.py`
///   and has to be re-run and re-committed by hand. A glyph added to
///   `tool/equipment_glyphs.py` without that rebuild is a constant pointing
///   into an unmapped code point.
///
/// Only the two fonts this repo ships are checked. `Icons.*` comes from
/// Flutter's own MaterialIcons font, which is not ours to vouch for.
void main() {
  const vendored = <String, String>{
    SubmersionIcons.fontFamily: 'assets/fonts/submersion-equipment.ttf',
    MdiIcons.fontFamily: 'assets/fonts/materialdesignicons-webfont.ttf',
  };

  final cmaps = <String, _Cmap>{
    for (final entry in vendored.entries)
      entry.key: _Cmap.fromFile(File(entry.value)),
  };

  test('both vendored fonts are present and parse', () {
    for (final entry in vendored.entries) {
      expect(
        File(entry.value).existsSync(),
        isTrue,
        reason: '${entry.value} is declared in pubspec.yaml but not committed',
      );
      expect(
        cmaps[entry.key]!.isEmpty,
        isFalse,
        reason: '${entry.value} has no usable Unicode cmap subtable',
      );
    }
  });

  test('every equipment glyph resolves in the font it names', () {
    final missing = <String>[];
    for (final type in EquipmentType.values) {
      final icon = equipmentTypeIcon(type);
      final cmap = cmaps[icon.fontFamily];
      // Material's own font is Flutter's to guarantee, not ours.
      if (cmap == null) continue;
      if (!cmap.maps(icon.codePoint)) {
        missing.add(
          '${type.name}: U+${icon.codePoint.toRadixString(16).toUpperCase()} '
          'is not mapped by ${icon.fontFamily}',
        );
      }
    }
    expect(missing, isEmpty, reason: missing.join('\n'));
  });

  test('the drawn glyph font maps every constant, not just the used ones', () {
    // `SubmersionIcons` is small and entirely ours, so it is checked whole:
    // a constant added ahead of the font rebuild fails here even before an
    // equipment type points at it.
    const drawn = <String, IconData>{
      'wetsuit': SubmersionIcons.wetsuit,
      'gloves': SubmersionIcons.gloves,
      'boots': SubmersionIcons.boots,
      'drysuit': SubmersionIcons.drysuit,
      'regulator': SubmersionIcons.regulator,
      'bcd': SubmersionIcons.bcd,
      'rebreather': SubmersionIcons.rebreather,
      'hood': SubmersionIcons.hood,
      'reel': SubmersionIcons.reel,
      'dpv': SubmersionIcons.dpv,
      'undersuit': SubmersionIcons.undersuit,
      'baselayer': SubmersionIcons.baselayer,
    };
    final cmap = cmaps[SubmersionIcons.fontFamily]!;
    for (final entry in drawn.entries) {
      expect(
        cmap.maps(entry.value.codePoint),
        isTrue,
        reason:
            '${entry.key} points at U+'
            '${entry.value.codePoint.toRadixString(16).toUpperCase()}, which '
            'the committed font does not map. Re-run '
            'tool/build_equipment_icon_font.py and commit the .ttf.',
      );
    }
  });

  group('the format 12 lookup derives a glyph id, not just containment', () {
    // Neither vendored font maps a code point onto glyph 0, so the real
    // files cannot exercise the .notdef branch. A hand-built font can: this
    // is a minimal sfnt carrying one format 12 subtable whose first group
    // starts at glyph 0, so the group contains two code points that derive
    // different answers.
    late Directory dir;
    late _Cmap cmap;

    setUpAll(() {
      dir = Directory.systemTemp.createTempSync('submersion_cmap_');
      final file = File('${dir.path}/format12.ttf')
        ..writeAsBytesSync(_syntheticFormat12Font());
      cmap = _Cmap.fromFile(file);
    });

    tearDownAll(() => dir.deleteSync(recursive: true));

    test('the subtable is found at all', () {
      expect(cmap.isEmpty, isFalse);
    });

    test('a code point deriving glyph 0 is not a mapping', () {
      // Inside the group, but startGlyphID 0 + offset 0 is .notdef.
      expect(cmap.maps(0xE000), isFalse);
    });

    test('the next code point in the same group is', () {
      // Same group, so a containment-only lookup answers the same for both.
      expect(cmap.maps(0xE001), isTrue);
    });

    test('a later group past the BMP resolves', () {
      expect(cmap.maps(0xF0000), isTrue);
    });

    test('code points outside every group do not', () {
      expect(cmap.maps(0xDFFF), isFalse);
      expect(cmap.maps(0xE002), isFalse);
      expect(cmap.maps(0xF0001), isFalse);
    });
  });

  test('a code point the fonts do not have is reported as missing', () {
    // Guards the parser itself: a `maps` that answered true for everything
    // would make all of the above vacuous.
    for (final cmap in cmaps.values) {
      expect(cmap.maps(0x0E0FFF), isFalse);
    }
    // And one it does have, so a `maps` that answered false for everything
    // could not hide either.
    expect(cmaps[SubmersionIcons.fontFamily]!.maps(0xE900), isTrue);
    expect(
      cmaps[MdiIcons.fontFamily]!.maps(MdiIcons.compass.codePoint),
      isTrue,
    );
  });
}

/// The Unicode character-to-glyph subtables of one TrueType font, queried one
/// code point at a time.
///
/// Only the two subtable formats the vendored fonts use are understood:
/// format 4 for the BMP (the Submersion font's private-use range) and format
/// 12 for the supplementary planes (Material Design Icons lives in Plane 15).
class _Cmap {
  _Cmap._(this._data, this._subtables);

  final ByteData _data;
  final List<int> _subtables;

  bool get isEmpty => _subtables.isEmpty;

  static _Cmap fromFile(File file) {
    if (!file.existsSync()) return _Cmap._(ByteData(0), const []);
    final data = ByteData.sublistView(file.readAsBytesSync());
    final tableCount = data.getUint16(4);
    int? cmapOffset;
    for (var i = 0; i < tableCount; i++) {
      final record = 12 + i * 16;
      final tag = String.fromCharCodes([
        for (var b = 0; b < 4; b++) data.getUint8(record + b),
      ]);
      if (tag == 'cmap') {
        cmapOffset = data.getUint32(record + 8);
        break;
      }
    }
    if (cmapOffset == null) return _Cmap._(data, const []);

    final subtables = <int>[];
    final encodingCount = data.getUint16(cmapOffset + 2);
    for (var i = 0; i < encodingCount; i++) {
      final record = cmapOffset + 4 + i * 8;
      final platformId = data.getUint16(record);
      final encodingId = data.getUint16(record + 2);
      // Unicode (platform 0) or Windows BMP/full-repertoire (3/1, 3/10).
      final isUnicode =
          platformId == 0 ||
          (platformId == 3 && (encodingId == 1 || encodingId == 10));
      if (!isUnicode) continue;
      final offset = cmapOffset + data.getUint32(record + 4);
      final format = data.getUint16(offset);
      if (format == 4 || format == 12) subtables.add(offset);
    }
    return _Cmap._(data, subtables);
  }

  /// Whether [codePoint] maps to a real (non-zero) glyph in any subtable.
  bool maps(int codePoint) {
    for (final offset in _subtables) {
      final found = switch (_data.getUint16(offset)) {
        4 => _mapsFormat4(offset, codePoint),
        12 => _mapsFormat12(offset, codePoint),
        _ => false,
      };
      if (found) return true;
    }
    return false;
  }

  bool _mapsFormat4(int sub, int codePoint) {
    if (codePoint > 0xFFFF) return false;
    final segCount = _data.getUint16(sub + 6) ~/ 2;
    final endCodes = sub + 14;
    final startCodes = endCodes + segCount * 2 + 2;
    final idDeltas = startCodes + segCount * 2;
    final idRangeOffsets = idDeltas + segCount * 2;
    for (var s = 0; s < segCount; s++) {
      final end = _data.getUint16(endCodes + s * 2);
      if (codePoint > end) continue;
      final start = _data.getUint16(startCodes + s * 2);
      if (codePoint < start) return false; // Segments are sorted.
      final delta = _data.getInt16(idDeltas + s * 2);
      final rangeOffset = _data.getUint16(idRangeOffsets + s * 2);
      if (rangeOffset == 0) return (codePoint + delta) & 0xFFFF != 0;
      final glyphAt =
          idRangeOffsets + s * 2 + rangeOffset + (codePoint - start) * 2;
      if (glyphAt + 1 >= _data.lengthInBytes) return false;
      return _data.getUint16(glyphAt) != 0;
    }
    return false;
  }

  bool _mapsFormat12(int sub, int codePoint) {
    final groupCount = _data.getUint32(sub + 12);
    for (var g = 0; g < groupCount; g++) {
      final record = sub + 16 + g * 12;
      final start = _data.getUint32(record);
      if (codePoint < start) return false; // Groups are sorted.
      if (codePoint > _data.getUint32(record + 4)) continue;
      // A group carries a startGlyphID that advances with the code point
      // across it, so containment alone is not a mapping: a group can run
      // through glyph 0 (.notdef). Derive the id and hold it to the same
      // non-zero contract the format 4 path applies.
      final glyphId = _data.getUint32(record + 8) + (codePoint - start);
      return glyphId != 0;
    }
    return false;
  }
}

/// A minimal TrueType container holding nothing but a `cmap` with one format
/// 12 subtable, used to reach the .notdef branch that real fonts never take.
///
/// Two groups: U+E000..U+E001 starting at glyph 0 (so the first code point in
/// it derives .notdef and the second does not), and U+F0000 starting at glyph
/// 5. Only the bytes [_Cmap] reads are filled in; this is not a loadable font.
Uint8List _syntheticFormat12Font() {
  const headerLength = 12;
  const recordLength = 16;
  const cmapStart = headerLength + recordLength;
  const subtableStart = cmapStart + 12;
  const groupCount = 2;
  const subtableLength = 16 + groupCount * 12;

  final bytes = Uint8List(subtableStart + subtableLength);
  final data = ByteData.sublistView(bytes);

  data.setUint32(0, 0x00010000); // sfntVersion
  data.setUint16(4, 1); // numTables

  bytes.setAll(headerLength, 'cmap'.codeUnits);
  data.setUint32(headerLength + 8, cmapStart);
  data.setUint32(headerLength + 12, bytes.length - cmapStart);

  data.setUint16(cmapStart, 0); // cmap version
  data.setUint16(cmapStart + 2, 1); // subtable count
  data.setUint16(cmapStart + 4, 3); // platformID: Windows
  data.setUint16(cmapStart + 6, 10); // encodingID: full repertoire
  data.setUint32(cmapStart + 8, subtableStart - cmapStart);

  data.setUint16(subtableStart, 12); // format
  data.setUint32(subtableStart + 4, subtableLength);
  data.setUint32(subtableStart + 12, groupCount);

  void group(int index, int start, int end, int startGlyphId) {
    final at = subtableStart + 16 + index * 12;
    data.setUint32(at, start);
    data.setUint32(at + 4, end);
    data.setUint32(at + 8, startGlyphId);
  }

  group(0, 0xE000, 0xE001, 0);
  group(1, 0xF0000, 0xF0000, 5);
  return bytes;
}
